// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "exp_24_16_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic exp_24_16_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic exp_24_16_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> exp_24_16_s::ap_ST_fsm_pp0_stage0 = "1";
const bool exp_24_16_s::ap_const_boolean_1 = true;
const sc_lv<32> exp_24_16_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool exp_24_16_s::ap_const_boolean_0 = false;
const sc_lv<32> exp_24_16_s::ap_const_lv32_D = "1101";
const sc_lv<32> exp_24_16_s::ap_const_lv32_5 = "101";
const sc_lv<32> exp_24_16_s::ap_const_lv32_B = "1011";
const sc_lv<3> exp_24_16_s::ap_const_lv3_0 = "000";
const sc_lv<32> exp_24_16_s::ap_const_lv32_29 = "101001";
const sc_lv<32> exp_24_16_s::ap_const_lv32_2D = "101101";
const sc_lv<32> exp_24_16_s::ap_const_lv32_34 = "110100";
const sc_lv<32> exp_24_16_s::ap_const_lv32_63 = "1100011";
const sc_lv<32> exp_24_16_s::ap_const_lv32_C = "1100";
const sc_lv<46> exp_24_16_s::ap_const_lv46_0 = "0000000000000000000000000000000000000000000000";
const sc_lv<46> exp_24_16_s::ap_const_lv46_1FFFFFFFFFFF = "111111111111111111111111111111111111111111111";
const sc_lv<32> exp_24_16_s::ap_const_lv32_4 = "100";
const sc_lv<32> exp_24_16_s::ap_const_lv32_31 = "110001";
const sc_lv<32> exp_24_16_s::ap_const_lv32_2C = "101100";
const sc_lv<32> exp_24_16_s::ap_const_lv32_2B = "101011";
const sc_lv<32> exp_24_16_s::ap_const_lv32_2A = "101010";
const sc_lv<32> exp_24_16_s::ap_const_lv32_28 = "101000";
const sc_lv<32> exp_24_16_s::ap_const_lv32_27 = "100111";
const sc_lv<32> exp_24_16_s::ap_const_lv32_26 = "100110";
const sc_lv<32> exp_24_16_s::ap_const_lv32_F = "1111";
const sc_lv<24> exp_24_16_s::ap_const_lv24_7FFFFF = "11111111111111111111111";

exp_24_16_s::exp_24_16_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    f_x_msb_2_table_U = new exp_24_16_s_f_x_mdEe("f_x_msb_2_table_U");
    f_x_msb_2_table_U->clk(ap_clk);
    f_x_msb_2_table_U->reset(ap_rst);
    f_x_msb_2_table_U->address0(f_x_msb_2_table_address0);
    f_x_msb_2_table_U->ce0(f_x_msb_2_table_ce0);
    f_x_msb_2_table_U->q0(f_x_msb_2_table_q0);
    exp_x_msb_1_table32_U = new exp_24_16_s_exp_xeOg("exp_x_msb_1_table32_U");
    exp_x_msb_1_table32_U->clk(ap_clk);
    exp_x_msb_1_table32_U->reset(ap_rst);
    exp_x_msb_1_table32_U->address0(exp_x_msb_1_table32_address0);
    exp_x_msb_1_table32_U->ce0(exp_x_msb_1_table32_ce0);
    exp_x_msb_1_table32_U->q0(exp_x_msb_1_table32_q0);
    MASTER_CNN_mul_50fYi_U604 = new MASTER_CNN_mul_50fYi<1,2,50,50,100>("MASTER_CNN_mul_50fYi_U604");
    MASTER_CNN_mul_50fYi_U604->clk(ap_clk);
    MASTER_CNN_mul_50fYi_U604->reset(ap_rst);
    MASTER_CNN_mul_50fYi_U604->din0(grp_fu_200_p0);
    MASTER_CNN_mul_50fYi_U604->din1(grp_fu_200_p1);
    MASTER_CNN_mul_50fYi_U604->ce(ap_var_for_const0);
    MASTER_CNN_mul_50fYi_U604->dout(grp_fu_200_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_ap_idle_pp0_0to3);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to3 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_8_fu_361_p2 );
    sensitive << ( tmp_6_fu_367_p4 );

    SC_METHOD(thread_exp_x_msb_1_table32_address0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_3_fu_155_p1 );

    SC_METHOD(thread_exp_x_msb_1_table32_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_f_x_msb_2_table_address0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_s_fu_150_p1 );

    SC_METHOD(thread_f_x_msb_2_table_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_200_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( grp_fu_200_p00 );

    SC_METHOD(thread_grp_fu_200_p00);
    sensitive << ( p_Result_1_fu_187_p3 );

    SC_METHOD(thread_grp_fu_200_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( grp_fu_200_p10 );

    SC_METHOD(thread_grp_fu_200_p10);
    sensitive << ( p_Val2_8_reg_421 );

    SC_METHOD(thread_loc_V_1_fu_160_p4);
    sensitive << ( f_x_msb_2_table_q0 );

    SC_METHOD(thread_loc_V_fu_142_p3);
    sensitive << ( tmp_7_fu_138_p1 );

    SC_METHOD(thread_not_s_fu_223_p2);
    sensitive << ( ap_reg_pp0_iter3_tmp_reg_390 );
    sensitive << ( tmp_4_fu_216_p3 );

    SC_METHOD(thread_p_Result_1_fu_187_p3);
    sensitive << ( r_V_3_reg_411 );
    sensitive << ( tmp_9_reg_416 );

    SC_METHOD(thread_p_Result_s_25_fu_130_p3);
    sensitive << ( tmp_fu_112_p3 );
    sensitive << ( p_Result_s_fu_120_p4 );

    SC_METHOD(thread_p_Result_s_fu_120_p4);
    sensitive << ( x_V );

    SC_METHOD(thread_p_Val2_10_fu_253_p3);
    sensitive << ( not_s_fu_223_p2 );
    sensitive << ( p_cast_cast_cast_fu_228_p3 );
    sensitive << ( y_V_fu_243_p4 );

    SC_METHOD(thread_p_Val2_9_fu_238_p2);
    sensitive << ( ap_reg_pp0_iter3_p_Val2_8_reg_421 );
    sensitive << ( tmp_5_fu_235_p1 );

    SC_METHOD(thread_p_cast_cast_cast_fu_228_p3);
    sensitive << ( ap_reg_pp0_iter3_tmp_reg_390 );

    SC_METHOD(thread_r_V_3_fu_177_p2);
    sensitive << ( tmp_2_fu_174_p1 );
    sensitive << ( tmp_1_fu_170_p1 );

    SC_METHOD(thread_tmp3_fu_337_p2);
    sensitive << ( tmp5_fu_331_p2 );
    sensitive << ( tmp4_fu_325_p2 );

    SC_METHOD(thread_tmp4_fu_325_p2);
    sensitive << ( tmp_10_fu_261_p3 );
    sensitive << ( tmp_11_fu_269_p3 );

    SC_METHOD(thread_tmp5_fu_331_p2);
    sensitive << ( tmp_12_fu_277_p3 );
    sensitive << ( tmp_13_fu_285_p3 );

    SC_METHOD(thread_tmp6_fu_355_p2);
    sensitive << ( tmp8_fu_349_p2 );
    sensitive << ( tmp7_fu_343_p2 );

    SC_METHOD(thread_tmp7_fu_343_p2);
    sensitive << ( tmp_14_fu_293_p3 );
    sensitive << ( tmp_15_fu_301_p3 );

    SC_METHOD(thread_tmp8_fu_349_p2);
    sensitive << ( tmp_16_fu_309_p3 );
    sensitive << ( tmp_17_fu_317_p3 );

    SC_METHOD(thread_tmp_10_fu_261_p3);
    sensitive << ( p_Val2_10_fu_253_p3 );

    SC_METHOD(thread_tmp_11_fu_269_p3);
    sensitive << ( p_Val2_10_fu_253_p3 );

    SC_METHOD(thread_tmp_12_fu_277_p3);
    sensitive << ( p_Val2_10_fu_253_p3 );

    SC_METHOD(thread_tmp_13_fu_285_p3);
    sensitive << ( p_Val2_10_fu_253_p3 );

    SC_METHOD(thread_tmp_14_fu_293_p3);
    sensitive << ( p_Val2_10_fu_253_p3 );

    SC_METHOD(thread_tmp_15_fu_301_p3);
    sensitive << ( p_Val2_10_fu_253_p3 );

    SC_METHOD(thread_tmp_16_fu_309_p3);
    sensitive << ( p_Val2_10_fu_253_p3 );

    SC_METHOD(thread_tmp_17_fu_317_p3);
    sensitive << ( p_Val2_10_fu_253_p3 );

    SC_METHOD(thread_tmp_1_fu_170_p1);
    sensitive << ( loc_V_1_fu_160_p4 );

    SC_METHOD(thread_tmp_2_fu_174_p1);
    sensitive << ( loc_V_reg_396 );

    SC_METHOD(thread_tmp_3_fu_155_p1);
    sensitive << ( p_Result_s_25_fu_130_p3 );

    SC_METHOD(thread_tmp_4_fu_216_p3);
    sensitive << ( ap_reg_pp0_iter3_x_V_read_reg_385 );

    SC_METHOD(thread_tmp_5_fu_235_p1);
    sensitive << ( p_Val2_7_reg_437 );

    SC_METHOD(thread_tmp_6_fu_367_p4);
    sensitive << ( p_Val2_10_fu_253_p3 );

    SC_METHOD(thread_tmp_7_fu_138_p1);
    sensitive << ( x_V );

    SC_METHOD(thread_tmp_8_fu_361_p2);
    sensitive << ( tmp6_fu_355_p2 );
    sensitive << ( tmp3_fu_337_p2 );

    SC_METHOD(thread_tmp_9_fu_183_p1);
    sensitive << ( f_x_msb_2_table_q0 );

    SC_METHOD(thread_tmp_fu_112_p3);
    sensitive << ( x_V );

    SC_METHOD(thread_tmp_s_fu_150_p1);
    sensitive << ( loc_V_fu_142_p3 );

    SC_METHOD(thread_y_V_fu_243_p4);
    sensitive << ( p_Val2_9_fu_238_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "exp_24_16_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x_V, "(port)x_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4, "ap_block_state5_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, f_x_msb_2_table_address0, "f_x_msb_2_table_address0");
    sc_trace(mVcdFile, f_x_msb_2_table_ce0, "f_x_msb_2_table_ce0");
    sc_trace(mVcdFile, f_x_msb_2_table_q0, "f_x_msb_2_table_q0");
    sc_trace(mVcdFile, exp_x_msb_1_table32_address0, "exp_x_msb_1_table32_address0");
    sc_trace(mVcdFile, exp_x_msb_1_table32_ce0, "exp_x_msb_1_table32_ce0");
    sc_trace(mVcdFile, exp_x_msb_1_table32_q0, "exp_x_msb_1_table32_q0");
    sc_trace(mVcdFile, x_V_read_reg_385, "x_V_read_reg_385");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_x_V_read_reg_385, "ap_reg_pp0_iter1_x_V_read_reg_385");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_x_V_read_reg_385, "ap_reg_pp0_iter2_x_V_read_reg_385");
    sc_trace(mVcdFile, ap_reg_pp0_iter3_x_V_read_reg_385, "ap_reg_pp0_iter3_x_V_read_reg_385");
    sc_trace(mVcdFile, tmp_fu_112_p3, "tmp_fu_112_p3");
    sc_trace(mVcdFile, tmp_reg_390, "tmp_reg_390");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_tmp_reg_390, "ap_reg_pp0_iter1_tmp_reg_390");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_tmp_reg_390, "ap_reg_pp0_iter2_tmp_reg_390");
    sc_trace(mVcdFile, ap_reg_pp0_iter3_tmp_reg_390, "ap_reg_pp0_iter3_tmp_reg_390");
    sc_trace(mVcdFile, loc_V_fu_142_p3, "loc_V_fu_142_p3");
    sc_trace(mVcdFile, loc_V_reg_396, "loc_V_reg_396");
    sc_trace(mVcdFile, r_V_3_fu_177_p2, "r_V_3_fu_177_p2");
    sc_trace(mVcdFile, r_V_3_reg_411, "r_V_3_reg_411");
    sc_trace(mVcdFile, tmp_9_fu_183_p1, "tmp_9_fu_183_p1");
    sc_trace(mVcdFile, tmp_9_reg_416, "tmp_9_reg_416");
    sc_trace(mVcdFile, p_Val2_8_reg_421, "p_Val2_8_reg_421");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_p_Val2_8_reg_421, "ap_reg_pp0_iter2_p_Val2_8_reg_421");
    sc_trace(mVcdFile, ap_reg_pp0_iter3_p_Val2_8_reg_421, "ap_reg_pp0_iter3_p_Val2_8_reg_421");
    sc_trace(mVcdFile, p_Val2_7_reg_437, "p_Val2_7_reg_437");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, tmp_s_fu_150_p1, "tmp_s_fu_150_p1");
    sc_trace(mVcdFile, tmp_3_fu_155_p1, "tmp_3_fu_155_p1");
    sc_trace(mVcdFile, p_Result_s_fu_120_p4, "p_Result_s_fu_120_p4");
    sc_trace(mVcdFile, tmp_7_fu_138_p1, "tmp_7_fu_138_p1");
    sc_trace(mVcdFile, p_Result_s_25_fu_130_p3, "p_Result_s_25_fu_130_p3");
    sc_trace(mVcdFile, loc_V_1_fu_160_p4, "loc_V_1_fu_160_p4");
    sc_trace(mVcdFile, tmp_2_fu_174_p1, "tmp_2_fu_174_p1");
    sc_trace(mVcdFile, tmp_1_fu_170_p1, "tmp_1_fu_170_p1");
    sc_trace(mVcdFile, p_Result_1_fu_187_p3, "p_Result_1_fu_187_p3");
    sc_trace(mVcdFile, grp_fu_200_p0, "grp_fu_200_p0");
    sc_trace(mVcdFile, grp_fu_200_p1, "grp_fu_200_p1");
    sc_trace(mVcdFile, grp_fu_200_p2, "grp_fu_200_p2");
    sc_trace(mVcdFile, tmp_4_fu_216_p3, "tmp_4_fu_216_p3");
    sc_trace(mVcdFile, tmp_5_fu_235_p1, "tmp_5_fu_235_p1");
    sc_trace(mVcdFile, p_Val2_9_fu_238_p2, "p_Val2_9_fu_238_p2");
    sc_trace(mVcdFile, not_s_fu_223_p2, "not_s_fu_223_p2");
    sc_trace(mVcdFile, p_cast_cast_cast_fu_228_p3, "p_cast_cast_cast_fu_228_p3");
    sc_trace(mVcdFile, y_V_fu_243_p4, "y_V_fu_243_p4");
    sc_trace(mVcdFile, p_Val2_10_fu_253_p3, "p_Val2_10_fu_253_p3");
    sc_trace(mVcdFile, tmp_10_fu_261_p3, "tmp_10_fu_261_p3");
    sc_trace(mVcdFile, tmp_11_fu_269_p3, "tmp_11_fu_269_p3");
    sc_trace(mVcdFile, tmp_12_fu_277_p3, "tmp_12_fu_277_p3");
    sc_trace(mVcdFile, tmp_13_fu_285_p3, "tmp_13_fu_285_p3");
    sc_trace(mVcdFile, tmp5_fu_331_p2, "tmp5_fu_331_p2");
    sc_trace(mVcdFile, tmp4_fu_325_p2, "tmp4_fu_325_p2");
    sc_trace(mVcdFile, tmp_14_fu_293_p3, "tmp_14_fu_293_p3");
    sc_trace(mVcdFile, tmp_15_fu_301_p3, "tmp_15_fu_301_p3");
    sc_trace(mVcdFile, tmp_16_fu_309_p3, "tmp_16_fu_309_p3");
    sc_trace(mVcdFile, tmp_17_fu_317_p3, "tmp_17_fu_317_p3");
    sc_trace(mVcdFile, tmp8_fu_349_p2, "tmp8_fu_349_p2");
    sc_trace(mVcdFile, tmp7_fu_343_p2, "tmp7_fu_343_p2");
    sc_trace(mVcdFile, tmp6_fu_355_p2, "tmp6_fu_355_p2");
    sc_trace(mVcdFile, tmp3_fu_337_p2, "tmp3_fu_337_p2");
    sc_trace(mVcdFile, tmp_8_fu_361_p2, "tmp_8_fu_361_p2");
    sc_trace(mVcdFile, tmp_6_fu_367_p4, "tmp_6_fu_367_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to3, "ap_idle_pp0_0to3");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, grp_fu_200_p00, "grp_fu_200_p00");
    sc_trace(mVcdFile, grp_fu_200_p10, "grp_fu_200_p10");
#endif

    }
}

exp_24_16_s::~exp_24_16_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete f_x_msb_2_table_U;
    delete exp_x_msb_1_table32_U;
    delete MASTER_CNN_mul_50fYi_U604;
}

void exp_24_16_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void exp_24_16_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_reg_pp0_iter1_tmp_reg_390 = tmp_reg_390.read();
        ap_reg_pp0_iter1_x_V_read_reg_385 = x_V_read_reg_385.read();
        loc_V_reg_396 = loc_V_fu_142_p3.read();
        p_Val2_8_reg_421 = exp_x_msb_1_table32_q0.read();
        r_V_3_reg_411 = r_V_3_fu_177_p2.read();
        tmp_9_reg_416 = tmp_9_fu_183_p1.read();
        tmp_reg_390 = x_V.read().range(13, 13);
        x_V_read_reg_385 = x_V.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        ap_reg_pp0_iter2_p_Val2_8_reg_421 = p_Val2_8_reg_421.read();
        ap_reg_pp0_iter2_tmp_reg_390 = ap_reg_pp0_iter1_tmp_reg_390.read();
        ap_reg_pp0_iter2_x_V_read_reg_385 = ap_reg_pp0_iter1_x_V_read_reg_385.read();
        ap_reg_pp0_iter3_p_Val2_8_reg_421 = ap_reg_pp0_iter2_p_Val2_8_reg_421.read();
        ap_reg_pp0_iter3_tmp_reg_390 = ap_reg_pp0_iter2_tmp_reg_390.read();
        ap_reg_pp0_iter3_x_V_read_reg_385 = ap_reg_pp0_iter2_x_V_read_reg_385.read();
        p_Val2_7_reg_437 = grp_fu_200_p2.read().range(99, 52);
    }
}

void exp_24_16_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void exp_24_16_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_24_16_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()));
}

void exp_24_16_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()));
}

void exp_24_16_s::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read());
}

void exp_24_16_s::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_24_16_s::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_24_16_s::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_24_16_s::thread_ap_block_state5_pp0_stage0_iter4() {
    ap_block_state5_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_24_16_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void exp_24_16_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void exp_24_16_s::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void exp_24_16_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void exp_24_16_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void exp_24_16_s::thread_ap_idle_pp0_0to3() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0_0to3 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to3 = ap_const_logic_0;
    }
}

void exp_24_16_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void exp_24_16_s::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to3.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void exp_24_16_s::thread_ap_return() {
    ap_return = (!tmp_8_fu_361_p2.read()[0].is_01())? sc_lv<24>(): ((tmp_8_fu_361_p2.read()[0].to_bool())? ap_const_lv24_7FFFFF: tmp_6_fu_367_p4.read());
}

void exp_24_16_s::thread_exp_x_msb_1_table32_address0() {
    exp_x_msb_1_table32_address0 =  (sc_lv<8>) (tmp_3_fu_155_p1.read());
}

void exp_24_16_s::thread_exp_x_msb_1_table32_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exp_x_msb_1_table32_ce0 = ap_const_logic_1;
    } else {
        exp_x_msb_1_table32_ce0 = ap_const_logic_0;
    }
}

void exp_24_16_s::thread_f_x_msb_2_table_address0() {
    f_x_msb_2_table_address0 =  (sc_lv<8>) (tmp_s_fu_150_p1.read());
}

void exp_24_16_s::thread_f_x_msb_2_table_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        f_x_msb_2_table_ce0 = ap_const_logic_1;
    } else {
        f_x_msb_2_table_ce0 = ap_const_logic_0;
    }
}

void exp_24_16_s::thread_grp_fu_200_p0() {
    grp_fu_200_p0 =  (sc_lv<50>) (grp_fu_200_p00.read());
}

void exp_24_16_s::thread_grp_fu_200_p00() {
    grp_fu_200_p00 = esl_zext<100,50>(p_Result_1_fu_187_p3.read());
}

void exp_24_16_s::thread_grp_fu_200_p1() {
    grp_fu_200_p1 =  (sc_lv<50>) (grp_fu_200_p10.read());
}

void exp_24_16_s::thread_grp_fu_200_p10() {
    grp_fu_200_p10 = esl_zext<100,50>(p_Val2_8_reg_421.read());
}

void exp_24_16_s::thread_loc_V_1_fu_160_p4() {
    loc_V_1_fu_160_p4 = f_x_msb_2_table_q0.read().range(45, 41);
}

void exp_24_16_s::thread_loc_V_fu_142_p3() {
    loc_V_fu_142_p3 = esl_concat<5,3>(tmp_7_fu_138_p1.read(), ap_const_lv3_0);
}

void exp_24_16_s::thread_not_s_fu_223_p2() {
    not_s_fu_223_p2 = (tmp_4_fu_216_p3.read() ^ ap_reg_pp0_iter3_tmp_reg_390.read());
}

void exp_24_16_s::thread_p_Result_1_fu_187_p3() {
    p_Result_1_fu_187_p3 = esl_concat<9,41>(r_V_3_reg_411.read(), tmp_9_reg_416.read());
}

void exp_24_16_s::thread_p_Result_s_25_fu_130_p3() {
    p_Result_s_25_fu_130_p3 = esl_concat<1,7>(tmp_fu_112_p3.read(), p_Result_s_fu_120_p4.read());
}

void exp_24_16_s::thread_p_Result_s_fu_120_p4() {
    p_Result_s_fu_120_p4 = x_V.read().range(11, 5);
}

void exp_24_16_s::thread_p_Val2_10_fu_253_p3() {
    p_Val2_10_fu_253_p3 = (!not_s_fu_223_p2.read()[0].is_01())? sc_lv<46>(): ((not_s_fu_223_p2.read()[0].to_bool())? p_cast_cast_cast_fu_228_p3.read(): y_V_fu_243_p4.read());
}

void exp_24_16_s::thread_p_Val2_9_fu_238_p2() {
    p_Val2_9_fu_238_p2 = (!ap_reg_pp0_iter3_p_Val2_8_reg_421.read().is_01() || !tmp_5_fu_235_p1.read().is_01())? sc_lv<50>(): (sc_biguint<50>(ap_reg_pp0_iter3_p_Val2_8_reg_421.read()) + sc_biguint<50>(tmp_5_fu_235_p1.read()));
}

void exp_24_16_s::thread_p_cast_cast_cast_fu_228_p3() {
    p_cast_cast_cast_fu_228_p3 = (!ap_reg_pp0_iter3_tmp_reg_390.read()[0].is_01())? sc_lv<46>(): ((ap_reg_pp0_iter3_tmp_reg_390.read()[0].to_bool())? ap_const_lv46_0: ap_const_lv46_1FFFFFFFFFFF);
}

void exp_24_16_s::thread_r_V_3_fu_177_p2() {
    r_V_3_fu_177_p2 = (!tmp_2_fu_174_p1.read().is_01() || !tmp_1_fu_170_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_2_fu_174_p1.read()) + sc_biguint<9>(tmp_1_fu_170_p1.read()));
}

void exp_24_16_s::thread_tmp3_fu_337_p2() {
    tmp3_fu_337_p2 = (tmp5_fu_331_p2.read() | tmp4_fu_325_p2.read());
}

void exp_24_16_s::thread_tmp4_fu_325_p2() {
    tmp4_fu_325_p2 = (tmp_10_fu_261_p3.read() | tmp_11_fu_269_p3.read());
}

void exp_24_16_s::thread_tmp5_fu_331_p2() {
    tmp5_fu_331_p2 = (tmp_12_fu_277_p3.read() | tmp_13_fu_285_p3.read());
}

void exp_24_16_s::thread_tmp6_fu_355_p2() {
    tmp6_fu_355_p2 = (tmp8_fu_349_p2.read() | tmp7_fu_343_p2.read());
}

void exp_24_16_s::thread_tmp7_fu_343_p2() {
    tmp7_fu_343_p2 = (tmp_14_fu_293_p3.read() | tmp_15_fu_301_p3.read());
}

void exp_24_16_s::thread_tmp8_fu_349_p2() {
    tmp8_fu_349_p2 = (tmp_16_fu_309_p3.read() | tmp_17_fu_317_p3.read());
}

void exp_24_16_s::thread_tmp_10_fu_261_p3() {
    tmp_10_fu_261_p3 = p_Val2_10_fu_253_p3.read().range(45, 45);
}

void exp_24_16_s::thread_tmp_11_fu_269_p3() {
    tmp_11_fu_269_p3 = p_Val2_10_fu_253_p3.read().range(44, 44);
}

void exp_24_16_s::thread_tmp_12_fu_277_p3() {
    tmp_12_fu_277_p3 = p_Val2_10_fu_253_p3.read().range(43, 43);
}

void exp_24_16_s::thread_tmp_13_fu_285_p3() {
    tmp_13_fu_285_p3 = p_Val2_10_fu_253_p3.read().range(42, 42);
}

void exp_24_16_s::thread_tmp_14_fu_293_p3() {
    tmp_14_fu_293_p3 = p_Val2_10_fu_253_p3.read().range(41, 41);
}

void exp_24_16_s::thread_tmp_15_fu_301_p3() {
    tmp_15_fu_301_p3 = p_Val2_10_fu_253_p3.read().range(40, 40);
}

void exp_24_16_s::thread_tmp_16_fu_309_p3() {
    tmp_16_fu_309_p3 = p_Val2_10_fu_253_p3.read().range(39, 39);
}

void exp_24_16_s::thread_tmp_17_fu_317_p3() {
    tmp_17_fu_317_p3 = p_Val2_10_fu_253_p3.read().range(38, 38);
}

void exp_24_16_s::thread_tmp_1_fu_170_p1() {
    tmp_1_fu_170_p1 = esl_zext<9,5>(loc_V_1_fu_160_p4.read());
}

void exp_24_16_s::thread_tmp_2_fu_174_p1() {
    tmp_2_fu_174_p1 = esl_zext<9,8>(loc_V_reg_396.read());
}

void exp_24_16_s::thread_tmp_3_fu_155_p1() {
    tmp_3_fu_155_p1 = esl_zext<64,8>(p_Result_s_25_fu_130_p3.read());
}

void exp_24_16_s::thread_tmp_4_fu_216_p3() {
    tmp_4_fu_216_p3 = ap_reg_pp0_iter3_x_V_read_reg_385.read().range(12, 12);
}

void exp_24_16_s::thread_tmp_5_fu_235_p1() {
    tmp_5_fu_235_p1 = esl_zext<50,48>(p_Val2_7_reg_437.read());
}

void exp_24_16_s::thread_tmp_6_fu_367_p4() {
    tmp_6_fu_367_p4 = p_Val2_10_fu_253_p3.read().range(38, 15);
}

void exp_24_16_s::thread_tmp_7_fu_138_p1() {
    tmp_7_fu_138_p1 = x_V.read().range(5-1, 0);
}

void exp_24_16_s::thread_tmp_8_fu_361_p2() {
    tmp_8_fu_361_p2 = (tmp6_fu_355_p2.read() | tmp3_fu_337_p2.read());
}

void exp_24_16_s::thread_tmp_9_fu_183_p1() {
    tmp_9_fu_183_p1 = f_x_msb_2_table_q0.read().range(41-1, 0);
}

void exp_24_16_s::thread_tmp_fu_112_p3() {
    tmp_fu_112_p3 = x_V.read().range(13, 13);
}

void exp_24_16_s::thread_tmp_s_fu_150_p1() {
    tmp_s_fu_150_p1 = esl_zext<64,8>(loc_V_fu_142_p3.read());
}

void exp_24_16_s::thread_y_V_fu_243_p4() {
    y_V_fu_243_p4 = p_Val2_9_fu_238_p2.read().range(49, 4);
}

void exp_24_16_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

