// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Layer2_mult_inner.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Layer2_mult_inner::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Layer2_mult_inner::ap_const_logic_0 = sc_dt::Log_0;
const bool Layer2_mult_inner::ap_const_boolean_1 = true;
const bool Layer2_mult_inner::ap_const_boolean_0 = false;
const sc_lv<32> Layer2_mult_inner::ap_const_lv32_A = "1010";
const sc_lv<32> Layer2_mult_inner::ap_const_lv32_1B = "11011";
const sc_lv<10> Layer2_mult_inner::ap_const_lv10_0 = "0000000000";

Layer2_mult_inner::Layer2_mult_inner(sc_module_name name) : sc_module(name), mVcdFile(0) {
    MASTER_CNN_mul_mucud_U153 = new MASTER_CNN_mul_mucud<1,1,18,18,28>("MASTER_CNN_mul_mucud_U153");
    MASTER_CNN_mul_mucud_U153->din0(p_read_int_reg);
    MASTER_CNN_mul_mucud_U153->din1(weight_0_V_read_int_reg);
    MASTER_CNN_mul_mucud_U153->dout(p_Val2_s_fu_369_p2);
    MASTER_CNN_mac_mubkb_U154 = new MASTER_CNN_mac_mubkb<1,1,18,18,28,28>("MASTER_CNN_mac_mubkb_U154");
    MASTER_CNN_mac_mubkb_U154->din0(p_read_8_reg_523);
    MASTER_CNN_mac_mubkb_U154->din1(weight_1_V_read_1_reg_483);
    MASTER_CNN_mac_mubkb_U154->din2(grp_fu_376_p2);
    MASTER_CNN_mac_mubkb_U154->dout(grp_fu_376_p3);
    MASTER_CNN_mac_mubkb_U155 = new MASTER_CNN_mac_mubkb<1,1,18,18,28,28>("MASTER_CNN_mac_mubkb_U155");
    MASTER_CNN_mac_mubkb_U155->din0(p_read_7_reg_518);
    MASTER_CNN_mac_mubkb_U155->din1(weight_2_V_read_1_reg_478);
    MASTER_CNN_mac_mubkb_U155->din2(grp_fu_385_p2);
    MASTER_CNN_mac_mubkb_U155->dout(grp_fu_385_p3);
    MASTER_CNN_mac_mubkb_U156 = new MASTER_CNN_mac_mubkb<1,1,18,18,28,28>("MASTER_CNN_mac_mubkb_U156");
    MASTER_CNN_mac_mubkb_U156->din0(ap_reg_pp0_iter1_p_read_6_reg_513);
    MASTER_CNN_mac_mubkb_U156->din1(ap_reg_pp0_iter1_weight_3_V_read_1_reg_473);
    MASTER_CNN_mac_mubkb_U156->din2(grp_fu_394_p2);
    MASTER_CNN_mac_mubkb_U156->dout(grp_fu_394_p3);
    MASTER_CNN_mac_mubkb_U157 = new MASTER_CNN_mac_mubkb<1,1,18,18,28,28>("MASTER_CNN_mac_mubkb_U157");
    MASTER_CNN_mac_mubkb_U157->din0(ap_reg_pp0_iter1_p_read_5_reg_508);
    MASTER_CNN_mac_mubkb_U157->din1(ap_reg_pp0_iter1_weight_4_V_read_1_reg_468);
    MASTER_CNN_mac_mubkb_U157->din2(grp_fu_403_p2);
    MASTER_CNN_mac_mubkb_U157->dout(grp_fu_403_p3);
    MASTER_CNN_mac_mubkb_U158 = new MASTER_CNN_mac_mubkb<1,1,18,18,28,28>("MASTER_CNN_mac_mubkb_U158");
    MASTER_CNN_mac_mubkb_U158->din0(ap_reg_pp0_iter2_p_read_4_reg_503);
    MASTER_CNN_mac_mubkb_U158->din1(ap_reg_pp0_iter2_weight_5_V_read_1_reg_463);
    MASTER_CNN_mac_mubkb_U158->din2(grp_fu_412_p2);
    MASTER_CNN_mac_mubkb_U158->dout(grp_fu_412_p3);
    MASTER_CNN_mac_mubkb_U159 = new MASTER_CNN_mac_mubkb<1,1,18,18,28,28>("MASTER_CNN_mac_mubkb_U159");
    MASTER_CNN_mac_mubkb_U159->din0(ap_reg_pp0_iter2_p_read_3_reg_498);
    MASTER_CNN_mac_mubkb_U159->din1(ap_reg_pp0_iter2_weight_6_V_read_1_reg_458);
    MASTER_CNN_mac_mubkb_U159->din2(grp_fu_421_p2);
    MASTER_CNN_mac_mubkb_U159->dout(grp_fu_421_p3);
    MASTER_CNN_mac_mubkb_U160 = new MASTER_CNN_mac_mubkb<1,1,18,18,28,28>("MASTER_CNN_mac_mubkb_U160");
    MASTER_CNN_mac_mubkb_U160->din0(ap_reg_pp0_iter3_p_read_2_reg_493);
    MASTER_CNN_mac_mubkb_U160->din1(ap_reg_pp0_iter3_weight_7_V_read_1_reg_453);
    MASTER_CNN_mac_mubkb_U160->din2(grp_fu_430_p2);
    MASTER_CNN_mac_mubkb_U160->dout(grp_fu_430_p3);
    MASTER_CNN_mac_mubkb_U161 = new MASTER_CNN_mac_mubkb<1,1,18,18,28,28>("MASTER_CNN_mac_mubkb_U161");
    MASTER_CNN_mac_mubkb_U161->din0(ap_reg_pp0_iter3_p_read_1_reg_488);
    MASTER_CNN_mac_mubkb_U161->din1(ap_reg_pp0_iter3_weight_8_V_read_1_reg_448);
    MASTER_CNN_mac_mubkb_U161->din2(grp_fu_439_p2);
    MASTER_CNN_mac_mubkb_U161->dout(grp_fu_439_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4);

    SC_METHOD(thread_ap_return);
    sensitive << ( grp_fu_439_p3 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_int_reg );

    SC_METHOD(thread_grp_fu_376_p2);
    sensitive << ( tmp_25_reg_528 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_385_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_26_fu_208_p4 );

    SC_METHOD(thread_grp_fu_394_p2);
    sensitive << ( tmp_27_reg_533 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_403_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_28_fu_253_p4 );

    SC_METHOD(thread_grp_fu_412_p2);
    sensitive << ( tmp_29_reg_538 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_421_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_30_fu_298_p4 );

    SC_METHOD(thread_grp_fu_430_p2);
    sensitive << ( tmp_31_reg_543 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_439_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_32_fu_343_p4 );

    SC_METHOD(thread_tmp_26_fu_208_p4);
    sensitive << ( grp_fu_376_p3 );

    SC_METHOD(thread_tmp_28_fu_253_p4);
    sensitive << ( grp_fu_394_p3 );

    SC_METHOD(thread_tmp_30_fu_298_p4);
    sensitive << ( grp_fu_412_p3 );

    SC_METHOD(thread_tmp_32_fu_343_p4);
    sensitive << ( grp_fu_430_p3 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Layer2_mult_inner_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, p_read, "(port)p_read");
    sc_trace(mVcdFile, p_read1, "(port)p_read1");
    sc_trace(mVcdFile, p_read2, "(port)p_read2");
    sc_trace(mVcdFile, p_read3, "(port)p_read3");
    sc_trace(mVcdFile, p_read4, "(port)p_read4");
    sc_trace(mVcdFile, p_read5, "(port)p_read5");
    sc_trace(mVcdFile, p_read6, "(port)p_read6");
    sc_trace(mVcdFile, p_read7, "(port)p_read7");
    sc_trace(mVcdFile, p_read8, "(port)p_read8");
    sc_trace(mVcdFile, weight_0_V_read, "(port)weight_0_V_read");
    sc_trace(mVcdFile, weight_1_V_read, "(port)weight_1_V_read");
    sc_trace(mVcdFile, weight_2_V_read, "(port)weight_2_V_read");
    sc_trace(mVcdFile, weight_3_V_read, "(port)weight_3_V_read");
    sc_trace(mVcdFile, weight_4_V_read, "(port)weight_4_V_read");
    sc_trace(mVcdFile, weight_5_V_read, "(port)weight_5_V_read");
    sc_trace(mVcdFile, weight_6_V_read, "(port)weight_6_V_read");
    sc_trace(mVcdFile, weight_7_V_read, "(port)weight_7_V_read");
    sc_trace(mVcdFile, weight_8_V_read, "(port)weight_8_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, weight_8_V_read_1_reg_448, "weight_8_V_read_1_reg_448");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4, "ap_block_state5_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_weight_8_V_read_1_reg_448, "ap_reg_pp0_iter1_weight_8_V_read_1_reg_448");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_weight_8_V_read_1_reg_448, "ap_reg_pp0_iter2_weight_8_V_read_1_reg_448");
    sc_trace(mVcdFile, ap_reg_pp0_iter3_weight_8_V_read_1_reg_448, "ap_reg_pp0_iter3_weight_8_V_read_1_reg_448");
    sc_trace(mVcdFile, weight_7_V_read_1_reg_453, "weight_7_V_read_1_reg_453");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_weight_7_V_read_1_reg_453, "ap_reg_pp0_iter1_weight_7_V_read_1_reg_453");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_weight_7_V_read_1_reg_453, "ap_reg_pp0_iter2_weight_7_V_read_1_reg_453");
    sc_trace(mVcdFile, ap_reg_pp0_iter3_weight_7_V_read_1_reg_453, "ap_reg_pp0_iter3_weight_7_V_read_1_reg_453");
    sc_trace(mVcdFile, weight_6_V_read_1_reg_458, "weight_6_V_read_1_reg_458");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_weight_6_V_read_1_reg_458, "ap_reg_pp0_iter1_weight_6_V_read_1_reg_458");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_weight_6_V_read_1_reg_458, "ap_reg_pp0_iter2_weight_6_V_read_1_reg_458");
    sc_trace(mVcdFile, weight_5_V_read_1_reg_463, "weight_5_V_read_1_reg_463");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_weight_5_V_read_1_reg_463, "ap_reg_pp0_iter1_weight_5_V_read_1_reg_463");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_weight_5_V_read_1_reg_463, "ap_reg_pp0_iter2_weight_5_V_read_1_reg_463");
    sc_trace(mVcdFile, weight_4_V_read_1_reg_468, "weight_4_V_read_1_reg_468");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_weight_4_V_read_1_reg_468, "ap_reg_pp0_iter1_weight_4_V_read_1_reg_468");
    sc_trace(mVcdFile, weight_3_V_read_1_reg_473, "weight_3_V_read_1_reg_473");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_weight_3_V_read_1_reg_473, "ap_reg_pp0_iter1_weight_3_V_read_1_reg_473");
    sc_trace(mVcdFile, weight_2_V_read_1_reg_478, "weight_2_V_read_1_reg_478");
    sc_trace(mVcdFile, weight_1_V_read_1_reg_483, "weight_1_V_read_1_reg_483");
    sc_trace(mVcdFile, p_read_1_reg_488, "p_read_1_reg_488");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_p_read_1_reg_488, "ap_reg_pp0_iter1_p_read_1_reg_488");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_p_read_1_reg_488, "ap_reg_pp0_iter2_p_read_1_reg_488");
    sc_trace(mVcdFile, ap_reg_pp0_iter3_p_read_1_reg_488, "ap_reg_pp0_iter3_p_read_1_reg_488");
    sc_trace(mVcdFile, p_read_2_reg_493, "p_read_2_reg_493");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_p_read_2_reg_493, "ap_reg_pp0_iter1_p_read_2_reg_493");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_p_read_2_reg_493, "ap_reg_pp0_iter2_p_read_2_reg_493");
    sc_trace(mVcdFile, ap_reg_pp0_iter3_p_read_2_reg_493, "ap_reg_pp0_iter3_p_read_2_reg_493");
    sc_trace(mVcdFile, p_read_3_reg_498, "p_read_3_reg_498");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_p_read_3_reg_498, "ap_reg_pp0_iter1_p_read_3_reg_498");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_p_read_3_reg_498, "ap_reg_pp0_iter2_p_read_3_reg_498");
    sc_trace(mVcdFile, p_read_4_reg_503, "p_read_4_reg_503");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_p_read_4_reg_503, "ap_reg_pp0_iter1_p_read_4_reg_503");
    sc_trace(mVcdFile, ap_reg_pp0_iter2_p_read_4_reg_503, "ap_reg_pp0_iter2_p_read_4_reg_503");
    sc_trace(mVcdFile, p_read_5_reg_508, "p_read_5_reg_508");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_p_read_5_reg_508, "ap_reg_pp0_iter1_p_read_5_reg_508");
    sc_trace(mVcdFile, p_read_6_reg_513, "p_read_6_reg_513");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_p_read_6_reg_513, "ap_reg_pp0_iter1_p_read_6_reg_513");
    sc_trace(mVcdFile, p_read_7_reg_518, "p_read_7_reg_518");
    sc_trace(mVcdFile, p_read_8_reg_523, "p_read_8_reg_523");
    sc_trace(mVcdFile, tmp_25_reg_528, "tmp_25_reg_528");
    sc_trace(mVcdFile, tmp_27_reg_533, "tmp_27_reg_533");
    sc_trace(mVcdFile, tmp_29_reg_538, "tmp_29_reg_538");
    sc_trace(mVcdFile, tmp_31_reg_543, "tmp_31_reg_543");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, p_Val2_s_fu_369_p2, "p_Val2_s_fu_369_p2");
    sc_trace(mVcdFile, grp_fu_376_p3, "grp_fu_376_p3");
    sc_trace(mVcdFile, tmp_26_fu_208_p4, "tmp_26_fu_208_p4");
    sc_trace(mVcdFile, grp_fu_385_p3, "grp_fu_385_p3");
    sc_trace(mVcdFile, grp_fu_394_p3, "grp_fu_394_p3");
    sc_trace(mVcdFile, tmp_28_fu_253_p4, "tmp_28_fu_253_p4");
    sc_trace(mVcdFile, grp_fu_403_p3, "grp_fu_403_p3");
    sc_trace(mVcdFile, grp_fu_412_p3, "grp_fu_412_p3");
    sc_trace(mVcdFile, tmp_30_fu_298_p4, "tmp_30_fu_298_p4");
    sc_trace(mVcdFile, grp_fu_421_p3, "grp_fu_421_p3");
    sc_trace(mVcdFile, grp_fu_430_p3, "grp_fu_430_p3");
    sc_trace(mVcdFile, tmp_32_fu_343_p4, "tmp_32_fu_343_p4");
    sc_trace(mVcdFile, grp_fu_439_p3, "grp_fu_439_p3");
    sc_trace(mVcdFile, grp_fu_376_p2, "grp_fu_376_p2");
    sc_trace(mVcdFile, grp_fu_385_p2, "grp_fu_385_p2");
    sc_trace(mVcdFile, grp_fu_394_p2, "grp_fu_394_p2");
    sc_trace(mVcdFile, grp_fu_403_p2, "grp_fu_403_p2");
    sc_trace(mVcdFile, grp_fu_412_p2, "grp_fu_412_p2");
    sc_trace(mVcdFile, grp_fu_421_p2, "grp_fu_421_p2");
    sc_trace(mVcdFile, grp_fu_430_p2, "grp_fu_430_p2");
    sc_trace(mVcdFile, grp_fu_439_p2, "grp_fu_439_p2");
    sc_trace(mVcdFile, ap_ce_reg, "ap_ce_reg");
    sc_trace(mVcdFile, p_read_int_reg, "p_read_int_reg");
    sc_trace(mVcdFile, p_read1_int_reg, "p_read1_int_reg");
    sc_trace(mVcdFile, p_read2_int_reg, "p_read2_int_reg");
    sc_trace(mVcdFile, p_read3_int_reg, "p_read3_int_reg");
    sc_trace(mVcdFile, p_read4_int_reg, "p_read4_int_reg");
    sc_trace(mVcdFile, p_read5_int_reg, "p_read5_int_reg");
    sc_trace(mVcdFile, p_read6_int_reg, "p_read6_int_reg");
    sc_trace(mVcdFile, p_read7_int_reg, "p_read7_int_reg");
    sc_trace(mVcdFile, p_read8_int_reg, "p_read8_int_reg");
    sc_trace(mVcdFile, weight_0_V_read_int_reg, "weight_0_V_read_int_reg");
    sc_trace(mVcdFile, weight_1_V_read_int_reg, "weight_1_V_read_int_reg");
    sc_trace(mVcdFile, weight_2_V_read_int_reg, "weight_2_V_read_int_reg");
    sc_trace(mVcdFile, weight_3_V_read_int_reg, "weight_3_V_read_int_reg");
    sc_trace(mVcdFile, weight_4_V_read_int_reg, "weight_4_V_read_int_reg");
    sc_trace(mVcdFile, weight_5_V_read_int_reg, "weight_5_V_read_int_reg");
    sc_trace(mVcdFile, weight_6_V_read_int_reg, "weight_6_V_read_int_reg");
    sc_trace(mVcdFile, weight_7_V_read_int_reg, "weight_7_V_read_int_reg");
    sc_trace(mVcdFile, weight_8_V_read_int_reg, "weight_8_V_read_int_reg");
    sc_trace(mVcdFile, ap_return_int_reg, "ap_return_int_reg");
#endif

    }
}

Layer2_mult_inner::~Layer2_mult_inner() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete MASTER_CNN_mul_mucud_U153;
    delete MASTER_CNN_mac_mubkb_U154;
    delete MASTER_CNN_mac_mubkb_U155;
    delete MASTER_CNN_mac_mubkb_U156;
    delete MASTER_CNN_mac_mubkb_U157;
    delete MASTER_CNN_mac_mubkb_U158;
    delete MASTER_CNN_mac_mubkb_U159;
    delete MASTER_CNN_mac_mubkb_U160;
    delete MASTER_CNN_mac_mubkb_U161;
}

void Layer2_mult_inner::thread_ap_clk_no_reset_() {
    ap_ce_reg = ap_ce.read();
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1))) {
        ap_reg_pp0_iter1_p_read_1_reg_488 = p_read_1_reg_488.read();
        ap_reg_pp0_iter1_p_read_2_reg_493 = p_read_2_reg_493.read();
        ap_reg_pp0_iter1_p_read_3_reg_498 = p_read_3_reg_498.read();
        ap_reg_pp0_iter1_p_read_4_reg_503 = p_read_4_reg_503.read();
        ap_reg_pp0_iter1_p_read_5_reg_508 = p_read_5_reg_508.read();
        ap_reg_pp0_iter1_p_read_6_reg_513 = p_read_6_reg_513.read();
        ap_reg_pp0_iter1_weight_3_V_read_1_reg_473 = weight_3_V_read_1_reg_473.read();
        ap_reg_pp0_iter1_weight_4_V_read_1_reg_468 = weight_4_V_read_1_reg_468.read();
        ap_reg_pp0_iter1_weight_5_V_read_1_reg_463 = weight_5_V_read_1_reg_463.read();
        ap_reg_pp0_iter1_weight_6_V_read_1_reg_458 = weight_6_V_read_1_reg_458.read();
        ap_reg_pp0_iter1_weight_7_V_read_1_reg_453 = weight_7_V_read_1_reg_453.read();
        ap_reg_pp0_iter1_weight_8_V_read_1_reg_448 = weight_8_V_read_1_reg_448.read();
        ap_reg_pp0_iter2_p_read_1_reg_488 = ap_reg_pp0_iter1_p_read_1_reg_488.read();
        ap_reg_pp0_iter2_p_read_2_reg_493 = ap_reg_pp0_iter1_p_read_2_reg_493.read();
        ap_reg_pp0_iter2_p_read_3_reg_498 = ap_reg_pp0_iter1_p_read_3_reg_498.read();
        ap_reg_pp0_iter2_p_read_4_reg_503 = ap_reg_pp0_iter1_p_read_4_reg_503.read();
        ap_reg_pp0_iter2_weight_5_V_read_1_reg_463 = ap_reg_pp0_iter1_weight_5_V_read_1_reg_463.read();
        ap_reg_pp0_iter2_weight_6_V_read_1_reg_458 = ap_reg_pp0_iter1_weight_6_V_read_1_reg_458.read();
        ap_reg_pp0_iter2_weight_7_V_read_1_reg_453 = ap_reg_pp0_iter1_weight_7_V_read_1_reg_453.read();
        ap_reg_pp0_iter2_weight_8_V_read_1_reg_448 = ap_reg_pp0_iter1_weight_8_V_read_1_reg_448.read();
        ap_reg_pp0_iter3_p_read_1_reg_488 = ap_reg_pp0_iter2_p_read_1_reg_488.read();
        ap_reg_pp0_iter3_p_read_2_reg_493 = ap_reg_pp0_iter2_p_read_2_reg_493.read();
        ap_reg_pp0_iter3_weight_7_V_read_1_reg_453 = ap_reg_pp0_iter2_weight_7_V_read_1_reg_453.read();
        ap_reg_pp0_iter3_weight_8_V_read_1_reg_448 = ap_reg_pp0_iter2_weight_8_V_read_1_reg_448.read();
        p_read_1_reg_488 = p_read8_int_reg.read();
        p_read_2_reg_493 = p_read7_int_reg.read();
        p_read_3_reg_498 = p_read6_int_reg.read();
        p_read_4_reg_503 = p_read5_int_reg.read();
        p_read_5_reg_508 = p_read4_int_reg.read();
        p_read_6_reg_513 = p_read3_int_reg.read();
        p_read_7_reg_518 = p_read2_int_reg.read();
        p_read_8_reg_523 = p_read1_int_reg.read();
        tmp_25_reg_528 = p_Val2_s_fu_369_p2.read().range(27, 10);
        tmp_27_reg_533 = grp_fu_385_p3.read().range(27, 10);
        tmp_29_reg_538 = grp_fu_403_p3.read().range(27, 10);
        tmp_31_reg_543 = grp_fu_421_p3.read().range(27, 10);
        weight_1_V_read_1_reg_483 = weight_1_V_read_int_reg.read();
        weight_2_V_read_1_reg_478 = weight_2_V_read_int_reg.read();
        weight_3_V_read_1_reg_473 = weight_3_V_read_int_reg.read();
        weight_4_V_read_1_reg_468 = weight_4_V_read_int_reg.read();
        weight_5_V_read_1_reg_463 = weight_5_V_read_int_reg.read();
        weight_6_V_read_1_reg_458 = weight_6_V_read_int_reg.read();
        weight_7_V_read_1_reg_453 = weight_7_V_read_int_reg.read();
        weight_8_V_read_1_reg_448 = weight_8_V_read_int_reg.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_int_reg = grp_fu_439_p3.read().range(27, 10);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read())) {
        p_read1_int_reg = p_read1.read();
        p_read2_int_reg = p_read2.read();
        p_read3_int_reg = p_read3.read();
        p_read4_int_reg = p_read4.read();
        p_read5_int_reg = p_read5.read();
        p_read6_int_reg = p_read6.read();
        p_read7_int_reg = p_read7.read();
        p_read8_int_reg = p_read8.read();
        p_read_int_reg = p_read.read();
        weight_0_V_read_int_reg = weight_0_V_read.read();
        weight_1_V_read_int_reg = weight_1_V_read.read();
        weight_2_V_read_int_reg = weight_2_V_read.read();
        weight_3_V_read_int_reg = weight_3_V_read.read();
        weight_4_V_read_int_reg = weight_4_V_read.read();
        weight_5_V_read_int_reg = weight_5_V_read.read();
        weight_6_V_read_int_reg = weight_6_V_read.read();
        weight_7_V_read_int_reg = weight_7_V_read.read();
        weight_8_V_read_int_reg = weight_8_V_read.read();
    }
}

void Layer2_mult_inner::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Layer2_mult_inner::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Layer2_mult_inner::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Layer2_mult_inner::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Layer2_mult_inner::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Layer2_mult_inner::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Layer2_mult_inner::thread_ap_block_state5_pp0_stage0_iter4() {
    ap_block_state5_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Layer2_mult_inner::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return = ap_return_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return = grp_fu_439_p3.read().range(27, 10);
    }
}

void Layer2_mult_inner::thread_grp_fu_376_p2() {
    grp_fu_376_p2 = esl_concat<18,10>(tmp_25_reg_528.read(), ap_const_lv10_0);
}

void Layer2_mult_inner::thread_grp_fu_385_p2() {
    grp_fu_385_p2 = esl_concat<18,10>(tmp_26_fu_208_p4.read(), ap_const_lv10_0);
}

void Layer2_mult_inner::thread_grp_fu_394_p2() {
    grp_fu_394_p2 = esl_concat<18,10>(tmp_27_reg_533.read(), ap_const_lv10_0);
}

void Layer2_mult_inner::thread_grp_fu_403_p2() {
    grp_fu_403_p2 = esl_concat<18,10>(tmp_28_fu_253_p4.read(), ap_const_lv10_0);
}

void Layer2_mult_inner::thread_grp_fu_412_p2() {
    grp_fu_412_p2 = esl_concat<18,10>(tmp_29_reg_538.read(), ap_const_lv10_0);
}

void Layer2_mult_inner::thread_grp_fu_421_p2() {
    grp_fu_421_p2 = esl_concat<18,10>(tmp_30_fu_298_p4.read(), ap_const_lv10_0);
}

void Layer2_mult_inner::thread_grp_fu_430_p2() {
    grp_fu_430_p2 = esl_concat<18,10>(tmp_31_reg_543.read(), ap_const_lv10_0);
}

void Layer2_mult_inner::thread_grp_fu_439_p2() {
    grp_fu_439_p2 = esl_concat<18,10>(tmp_32_fu_343_p4.read(), ap_const_lv10_0);
}

void Layer2_mult_inner::thread_tmp_26_fu_208_p4() {
    tmp_26_fu_208_p4 = grp_fu_376_p3.read().range(27, 10);
}

void Layer2_mult_inner::thread_tmp_28_fu_253_p4() {
    tmp_28_fu_253_p4 = grp_fu_394_p3.read().range(27, 10);
}

void Layer2_mult_inner::thread_tmp_30_fu_298_p4() {
    tmp_30_fu_298_p4 = grp_fu_412_p3.read().range(27, 10);
}

void Layer2_mult_inner::thread_tmp_32_fu_343_p4() {
    tmp_32_fu_343_p4 = grp_fu_430_p3.read().range(27, 10);
}

}

