// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _mult_add_HH_
#define _mult_add_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "MASTER_CNN_mac_mubkb.h"

namespace ap_rtl {

struct mult_add : public sc_module {
    // Port declarations 5
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<18> > in_V;
    sc_in< sc_lv<18> > weight_V;
    sc_in< sc_lv<18> > add_V;
    sc_out< sc_lv<18> > ap_return;


    // Module declarations
    mult_add(sc_module_name name);
    SC_HAS_PROCESS(mult_add);

    ~mult_add();

    sc_trace_file* mVcdFile;

    MASTER_CNN_mac_mubkb<1,1,18,18,28,28>* MASTER_CNN_mac_mubkb_U18;
    sc_signal< sc_lv<28> > grp_fu_71_p3;
    sc_signal< sc_lv<28> > grp_fu_71_p2;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_ready();
    void thread_ap_return();
    void thread_grp_fu_71_p2();
};

}

using namespace ap_rtl;

#endif
