// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mult_add (
        ap_ready,
        in_V,
        weight_V,
        add_V,
        ap_return
);


output   ap_ready;
input  [17:0] in_V;
input  [17:0] weight_V;
input  [17:0] add_V;
output  [17:0] ap_return;

wire  signed [27:0] grp_fu_71_p3;
wire   [27:0] grp_fu_71_p2;

MASTER_CNN_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
MASTER_CNN_mac_mubkb_U18(
    .din0(in_V),
    .din1(weight_V),
    .din2(grp_fu_71_p2),
    .dout(grp_fu_71_p3)
);

assign ap_ready = 1'b1;

assign ap_return = {{grp_fu_71_p3[27:10]}};

assign grp_fu_71_p2 = {{add_V}, {10'd0}};

endmodule //mult_add
