// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Layer2_mult_inner (
        ap_clk,
        ap_rst,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        weight_0_V_read,
        weight_1_V_read,
        weight_2_V_read,
        weight_3_V_read,
        weight_4_V_read,
        weight_5_V_read,
        weight_6_V_read,
        weight_7_V_read,
        weight_8_V_read,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [17:0] p_read;
input  [17:0] p_read1;
input  [17:0] p_read2;
input  [17:0] p_read3;
input  [17:0] p_read4;
input  [17:0] p_read5;
input  [17:0] p_read6;
input  [17:0] p_read7;
input  [17:0] p_read8;
input  [17:0] weight_0_V_read;
input  [17:0] weight_1_V_read;
input  [17:0] weight_2_V_read;
input  [17:0] weight_3_V_read;
input  [17:0] weight_4_V_read;
input  [17:0] weight_5_V_read;
input  [17:0] weight_6_V_read;
input  [17:0] weight_7_V_read;
input  [17:0] weight_8_V_read;
output  [17:0] ap_return;
input   ap_ce;

reg[17:0] ap_return;

reg   [17:0] weight_8_V_read_1_reg_448;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
reg   [17:0] ap_reg_pp0_iter1_weight_8_V_read_1_reg_448;
reg   [17:0] ap_reg_pp0_iter2_weight_8_V_read_1_reg_448;
reg  signed [17:0] ap_reg_pp0_iter3_weight_8_V_read_1_reg_448;
reg   [17:0] weight_7_V_read_1_reg_453;
reg   [17:0] ap_reg_pp0_iter1_weight_7_V_read_1_reg_453;
reg   [17:0] ap_reg_pp0_iter2_weight_7_V_read_1_reg_453;
reg  signed [17:0] ap_reg_pp0_iter3_weight_7_V_read_1_reg_453;
reg   [17:0] weight_6_V_read_1_reg_458;
reg   [17:0] ap_reg_pp0_iter1_weight_6_V_read_1_reg_458;
reg  signed [17:0] ap_reg_pp0_iter2_weight_6_V_read_1_reg_458;
reg   [17:0] weight_5_V_read_1_reg_463;
reg   [17:0] ap_reg_pp0_iter1_weight_5_V_read_1_reg_463;
reg  signed [17:0] ap_reg_pp0_iter2_weight_5_V_read_1_reg_463;
reg   [17:0] weight_4_V_read_1_reg_468;
reg  signed [17:0] ap_reg_pp0_iter1_weight_4_V_read_1_reg_468;
reg   [17:0] weight_3_V_read_1_reg_473;
reg  signed [17:0] ap_reg_pp0_iter1_weight_3_V_read_1_reg_473;
reg  signed [17:0] weight_2_V_read_1_reg_478;
reg  signed [17:0] weight_1_V_read_1_reg_483;
reg   [17:0] p_read_1_reg_488;
reg   [17:0] ap_reg_pp0_iter1_p_read_1_reg_488;
reg   [17:0] ap_reg_pp0_iter2_p_read_1_reg_488;
reg  signed [17:0] ap_reg_pp0_iter3_p_read_1_reg_488;
reg   [17:0] p_read_2_reg_493;
reg   [17:0] ap_reg_pp0_iter1_p_read_2_reg_493;
reg   [17:0] ap_reg_pp0_iter2_p_read_2_reg_493;
reg  signed [17:0] ap_reg_pp0_iter3_p_read_2_reg_493;
reg   [17:0] p_read_3_reg_498;
reg   [17:0] ap_reg_pp0_iter1_p_read_3_reg_498;
reg  signed [17:0] ap_reg_pp0_iter2_p_read_3_reg_498;
reg   [17:0] p_read_4_reg_503;
reg   [17:0] ap_reg_pp0_iter1_p_read_4_reg_503;
reg  signed [17:0] ap_reg_pp0_iter2_p_read_4_reg_503;
reg   [17:0] p_read_5_reg_508;
reg  signed [17:0] ap_reg_pp0_iter1_p_read_5_reg_508;
reg   [17:0] p_read_6_reg_513;
reg  signed [17:0] ap_reg_pp0_iter1_p_read_6_reg_513;
reg  signed [17:0] p_read_7_reg_518;
reg  signed [17:0] p_read_8_reg_523;
reg   [17:0] tmp_25_reg_528;
reg   [17:0] tmp_27_reg_533;
reg   [17:0] tmp_29_reg_538;
reg   [17:0] tmp_31_reg_543;
wire    ap_block_pp0_stage0;
wire  signed [27:0] p_Val2_s_fu_369_p2;
wire  signed [27:0] grp_fu_376_p3;
wire   [17:0] tmp_26_fu_208_p4;
wire  signed [27:0] grp_fu_385_p3;
wire  signed [27:0] grp_fu_394_p3;
wire   [17:0] tmp_28_fu_253_p4;
wire  signed [27:0] grp_fu_403_p3;
wire  signed [27:0] grp_fu_412_p3;
wire   [17:0] tmp_30_fu_298_p4;
wire  signed [27:0] grp_fu_421_p3;
wire  signed [27:0] grp_fu_430_p3;
wire   [17:0] tmp_32_fu_343_p4;
wire  signed [27:0] grp_fu_439_p3;
wire   [27:0] grp_fu_376_p2;
wire   [27:0] grp_fu_385_p2;
wire   [27:0] grp_fu_394_p2;
wire   [27:0] grp_fu_403_p2;
wire   [27:0] grp_fu_412_p2;
wire   [27:0] grp_fu_421_p2;
wire   [27:0] grp_fu_430_p2;
wire   [27:0] grp_fu_439_p2;
reg    ap_ce_reg;
reg  signed [17:0] p_read_int_reg;
reg   [17:0] p_read1_int_reg;
reg   [17:0] p_read2_int_reg;
reg   [17:0] p_read3_int_reg;
reg   [17:0] p_read4_int_reg;
reg   [17:0] p_read5_int_reg;
reg   [17:0] p_read6_int_reg;
reg   [17:0] p_read7_int_reg;
reg   [17:0] p_read8_int_reg;
reg  signed [17:0] weight_0_V_read_int_reg;
reg   [17:0] weight_1_V_read_int_reg;
reg   [17:0] weight_2_V_read_int_reg;
reg   [17:0] weight_3_V_read_int_reg;
reg   [17:0] weight_4_V_read_int_reg;
reg   [17:0] weight_5_V_read_int_reg;
reg   [17:0] weight_6_V_read_int_reg;
reg   [17:0] weight_7_V_read_int_reg;
reg   [17:0] weight_8_V_read_int_reg;
reg   [17:0] ap_return_int_reg;

MASTER_CNN_mul_mucud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 28 ))
MASTER_CNN_mul_mucud_U153(
    .din0(p_read_int_reg),
    .din1(weight_0_V_read_int_reg),
    .dout(p_Val2_s_fu_369_p2)
);

MASTER_CNN_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
MASTER_CNN_mac_mubkb_U154(
    .din0(p_read_8_reg_523),
    .din1(weight_1_V_read_1_reg_483),
    .din2(grp_fu_376_p2),
    .dout(grp_fu_376_p3)
);

MASTER_CNN_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
MASTER_CNN_mac_mubkb_U155(
    .din0(p_read_7_reg_518),
    .din1(weight_2_V_read_1_reg_478),
    .din2(grp_fu_385_p2),
    .dout(grp_fu_385_p3)
);

MASTER_CNN_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
MASTER_CNN_mac_mubkb_U156(
    .din0(ap_reg_pp0_iter1_p_read_6_reg_513),
    .din1(ap_reg_pp0_iter1_weight_3_V_read_1_reg_473),
    .din2(grp_fu_394_p2),
    .dout(grp_fu_394_p3)
);

MASTER_CNN_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
MASTER_CNN_mac_mubkb_U157(
    .din0(ap_reg_pp0_iter1_p_read_5_reg_508),
    .din1(ap_reg_pp0_iter1_weight_4_V_read_1_reg_468),
    .din2(grp_fu_403_p2),
    .dout(grp_fu_403_p3)
);

MASTER_CNN_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
MASTER_CNN_mac_mubkb_U158(
    .din0(ap_reg_pp0_iter2_p_read_4_reg_503),
    .din1(ap_reg_pp0_iter2_weight_5_V_read_1_reg_463),
    .din2(grp_fu_412_p2),
    .dout(grp_fu_412_p3)
);

MASTER_CNN_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
MASTER_CNN_mac_mubkb_U159(
    .din0(ap_reg_pp0_iter2_p_read_3_reg_498),
    .din1(ap_reg_pp0_iter2_weight_6_V_read_1_reg_458),
    .din2(grp_fu_421_p2),
    .dout(grp_fu_421_p3)
);

MASTER_CNN_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
MASTER_CNN_mac_mubkb_U160(
    .din0(ap_reg_pp0_iter3_p_read_2_reg_493),
    .din1(ap_reg_pp0_iter3_weight_7_V_read_1_reg_453),
    .din2(grp_fu_430_p2),
    .dout(grp_fu_430_p3)
);

MASTER_CNN_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
MASTER_CNN_mac_mubkb_U161(
    .din0(ap_reg_pp0_iter3_p_read_1_reg_488),
    .din1(ap_reg_pp0_iter3_weight_8_V_read_1_reg_448),
    .din2(grp_fu_439_p2),
    .dout(grp_fu_439_p3)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        ap_reg_pp0_iter1_p_read_1_reg_488 <= p_read_1_reg_488;
        ap_reg_pp0_iter1_p_read_2_reg_493 <= p_read_2_reg_493;
        ap_reg_pp0_iter1_p_read_3_reg_498 <= p_read_3_reg_498;
        ap_reg_pp0_iter1_p_read_4_reg_503 <= p_read_4_reg_503;
        ap_reg_pp0_iter1_p_read_5_reg_508 <= p_read_5_reg_508;
        ap_reg_pp0_iter1_p_read_6_reg_513 <= p_read_6_reg_513;
        ap_reg_pp0_iter1_weight_3_V_read_1_reg_473 <= weight_3_V_read_1_reg_473;
        ap_reg_pp0_iter1_weight_4_V_read_1_reg_468 <= weight_4_V_read_1_reg_468;
        ap_reg_pp0_iter1_weight_5_V_read_1_reg_463 <= weight_5_V_read_1_reg_463;
        ap_reg_pp0_iter1_weight_6_V_read_1_reg_458 <= weight_6_V_read_1_reg_458;
        ap_reg_pp0_iter1_weight_7_V_read_1_reg_453 <= weight_7_V_read_1_reg_453;
        ap_reg_pp0_iter1_weight_8_V_read_1_reg_448 <= weight_8_V_read_1_reg_448;
        ap_reg_pp0_iter2_p_read_1_reg_488 <= ap_reg_pp0_iter1_p_read_1_reg_488;
        ap_reg_pp0_iter2_p_read_2_reg_493 <= ap_reg_pp0_iter1_p_read_2_reg_493;
        ap_reg_pp0_iter2_p_read_3_reg_498 <= ap_reg_pp0_iter1_p_read_3_reg_498;
        ap_reg_pp0_iter2_p_read_4_reg_503 <= ap_reg_pp0_iter1_p_read_4_reg_503;
        ap_reg_pp0_iter2_weight_5_V_read_1_reg_463 <= ap_reg_pp0_iter1_weight_5_V_read_1_reg_463;
        ap_reg_pp0_iter2_weight_6_V_read_1_reg_458 <= ap_reg_pp0_iter1_weight_6_V_read_1_reg_458;
        ap_reg_pp0_iter2_weight_7_V_read_1_reg_453 <= ap_reg_pp0_iter1_weight_7_V_read_1_reg_453;
        ap_reg_pp0_iter2_weight_8_V_read_1_reg_448 <= ap_reg_pp0_iter1_weight_8_V_read_1_reg_448;
        ap_reg_pp0_iter3_p_read_1_reg_488 <= ap_reg_pp0_iter2_p_read_1_reg_488;
        ap_reg_pp0_iter3_p_read_2_reg_493 <= ap_reg_pp0_iter2_p_read_2_reg_493;
        ap_reg_pp0_iter3_weight_7_V_read_1_reg_453 <= ap_reg_pp0_iter2_weight_7_V_read_1_reg_453;
        ap_reg_pp0_iter3_weight_8_V_read_1_reg_448 <= ap_reg_pp0_iter2_weight_8_V_read_1_reg_448;
        p_read_1_reg_488 <= p_read8_int_reg;
        p_read_2_reg_493 <= p_read7_int_reg;
        p_read_3_reg_498 <= p_read6_int_reg;
        p_read_4_reg_503 <= p_read5_int_reg;
        p_read_5_reg_508 <= p_read4_int_reg;
        p_read_6_reg_513 <= p_read3_int_reg;
        p_read_7_reg_518 <= p_read2_int_reg;
        p_read_8_reg_523 <= p_read1_int_reg;
        tmp_25_reg_528 <= {{p_Val2_s_fu_369_p2[27:10]}};
        tmp_27_reg_533 <= {{grp_fu_385_p3[27:10]}};
        tmp_29_reg_538 <= {{grp_fu_403_p3[27:10]}};
        tmp_31_reg_543 <= {{grp_fu_421_p3[27:10]}};
        weight_1_V_read_1_reg_483 <= weight_1_V_read_int_reg;
        weight_2_V_read_1_reg_478 <= weight_2_V_read_int_reg;
        weight_3_V_read_1_reg_473 <= weight_3_V_read_int_reg;
        weight_4_V_read_1_reg_468 <= weight_4_V_read_int_reg;
        weight_5_V_read_1_reg_463 <= weight_5_V_read_int_reg;
        weight_6_V_read_1_reg_458 <= weight_6_V_read_int_reg;
        weight_7_V_read_1_reg_453 <= weight_7_V_read_int_reg;
        weight_8_V_read_1_reg_448 <= weight_8_V_read_int_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= {{grp_fu_439_p3[27:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        p_read1_int_reg <= p_read1;
        p_read2_int_reg <= p_read2;
        p_read3_int_reg <= p_read3;
        p_read4_int_reg <= p_read4;
        p_read5_int_reg <= p_read5;
        p_read6_int_reg <= p_read6;
        p_read7_int_reg <= p_read7;
        p_read8_int_reg <= p_read8;
        p_read_int_reg <= p_read;
        weight_0_V_read_int_reg <= weight_0_V_read;
        weight_1_V_read_int_reg <= weight_1_V_read;
        weight_2_V_read_int_reg <= weight_2_V_read;
        weight_3_V_read_int_reg <= weight_3_V_read;
        weight_4_V_read_int_reg <= weight_4_V_read;
        weight_5_V_read_int_reg <= weight_5_V_read;
        weight_6_V_read_int_reg <= weight_6_V_read;
        weight_7_V_read_int_reg <= weight_7_V_read;
        weight_8_V_read_int_reg <= weight_8_V_read;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = {{grp_fu_439_p3[27:10]}};
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign grp_fu_376_p2 = {{tmp_25_reg_528}, {10'd0}};

assign grp_fu_385_p2 = {{tmp_26_fu_208_p4}, {10'd0}};

assign grp_fu_394_p2 = {{tmp_27_reg_533}, {10'd0}};

assign grp_fu_403_p2 = {{tmp_28_fu_253_p4}, {10'd0}};

assign grp_fu_412_p2 = {{tmp_29_reg_538}, {10'd0}};

assign grp_fu_421_p2 = {{tmp_30_fu_298_p4}, {10'd0}};

assign grp_fu_430_p2 = {{tmp_31_reg_543}, {10'd0}};

assign grp_fu_439_p2 = {{tmp_32_fu_343_p4}, {10'd0}};

assign tmp_26_fu_208_p4 = {{grp_fu_376_p3[27:10]}};

assign tmp_28_fu_253_p4 = {{grp_fu_394_p3[27:10]}};

assign tmp_30_fu_298_p4 = {{grp_fu_412_p3[27:10]}};

assign tmp_32_fu_343_p4 = {{grp_fu_430_p3[27:10]}};

endmodule //Layer2_mult_inner
