// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MASTER_CNN,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.400000,HLS_SYN_LAT=378001,HLS_SYN_TPT=none,HLS_SYN_MEM=280,HLS_SYN_DSP=199,HLS_SYN_FF=35024,HLS_SYN_LUT=37287}" *)

module MASTER_CNN (
        ap_clk,
        ap_rst_n,
        saveValueLayer1_V_Addr_A,
        saveValueLayer1_V_EN_A,
        saveValueLayer1_V_WEN_A,
        saveValueLayer1_V_Din_A,
        saveValueLayer1_V_Dout_A,
        saveValueLayer1_V_Clk_A,
        saveValueLayer1_V_Rst_A,
        saveValueLayer2_V_Addr_A,
        saveValueLayer2_V_EN_A,
        saveValueLayer2_V_WEN_A,
        saveValueLayer2_V_Din_A,
        saveValueLayer2_V_Dout_A,
        saveValueLayer2_V_Clk_A,
        saveValueLayer2_V_Rst_A,
        saveValueLayer3_V_Addr_A,
        saveValueLayer3_V_EN_A,
        saveValueLayer3_V_WEN_A,
        saveValueLayer3_V_Din_A,
        saveValueLayer3_V_Dout_A,
        saveValueLayer3_V_Clk_A,
        saveValueLayer3_V_Rst_A,
        Layer1_WeightArray_V_Addr_A,
        Layer1_WeightArray_V_EN_A,
        Layer1_WeightArray_V_WEN_A,
        Layer1_WeightArray_V_Din_A,
        Layer1_WeightArray_V_Dout_A,
        Layer1_WeightArray_V_Clk_A,
        Layer1_WeightArray_V_Rst_A,
        Layer1_BiasArray_V_Addr_A,
        Layer1_BiasArray_V_EN_A,
        Layer1_BiasArray_V_WEN_A,
        Layer1_BiasArray_V_Din_A,
        Layer1_BiasArray_V_Dout_A,
        Layer1_BiasArray_V_Clk_A,
        Layer1_BiasArray_V_Rst_A,
        Layer2_WeightMatrix_V_Addr_A,
        Layer2_WeightMatrix_V_EN_A,
        Layer2_WeightMatrix_V_WEN_A,
        Layer2_WeightMatrix_V_Din_A,
        Layer2_WeightMatrix_V_Dout_A,
        Layer2_WeightMatrix_V_Clk_A,
        Layer2_WeightMatrix_V_Rst_A,
        Layer2_BiasArray_V_Addr_A,
        Layer2_BiasArray_V_EN_A,
        Layer2_BiasArray_V_WEN_A,
        Layer2_BiasArray_V_Din_A,
        Layer2_BiasArray_V_Dout_A,
        Layer2_BiasArray_V_Clk_A,
        Layer2_BiasArray_V_Rst_A,
        Layer3_weightArray_0_V_Addr_A,
        Layer3_weightArray_0_V_EN_A,
        Layer3_weightArray_0_V_WEN_A,
        Layer3_weightArray_0_V_Din_A,
        Layer3_weightArray_0_V_Dout_A,
        Layer3_weightArray_0_V_Clk_A,
        Layer3_weightArray_0_V_Rst_A,
        Layer3_weightArray_1_V_Addr_A,
        Layer3_weightArray_1_V_EN_A,
        Layer3_weightArray_1_V_WEN_A,
        Layer3_weightArray_1_V_Din_A,
        Layer3_weightArray_1_V_Dout_A,
        Layer3_weightArray_1_V_Clk_A,
        Layer3_weightArray_1_V_Rst_A,
        Layer3_weightArray_2_V_Addr_A,
        Layer3_weightArray_2_V_EN_A,
        Layer3_weightArray_2_V_WEN_A,
        Layer3_weightArray_2_V_Din_A,
        Layer3_weightArray_2_V_Dout_A,
        Layer3_weightArray_2_V_Clk_A,
        Layer3_weightArray_2_V_Rst_A,
        Layer3_weightArray_3_V_Addr_A,
        Layer3_weightArray_3_V_EN_A,
        Layer3_weightArray_3_V_WEN_A,
        Layer3_weightArray_3_V_Din_A,
        Layer3_weightArray_3_V_Dout_A,
        Layer3_weightArray_3_V_Clk_A,
        Layer3_weightArray_3_V_Rst_A,
        Layer3_Bias_V_Addr_A,
        Layer3_Bias_V_EN_A,
        Layer3_Bias_V_WEN_A,
        Layer3_Bias_V_Din_A,
        Layer3_Bias_V_Dout_A,
        Layer3_Bias_V_Clk_A,
        Layer3_Bias_V_Rst_A,
        Layer4_weightArray_V_Addr_A,
        Layer4_weightArray_V_EN_A,
        Layer4_weightArray_V_WEN_A,
        Layer4_weightArray_V_Din_A,
        Layer4_weightArray_V_Dout_A,
        Layer4_weightArray_V_Clk_A,
        Layer4_weightArray_V_Rst_A,
        Layer4_Bias_V_Addr_A,
        Layer4_Bias_V_EN_A,
        Layer4_Bias_V_WEN_A,
        Layer4_Bias_V_Din_A,
        Layer4_Bias_V_Dout_A,
        Layer4_Bias_V_Clk_A,
        Layer4_Bias_V_Rst_A,
        s_axi_BUS_A_AWVALID,
        s_axi_BUS_A_AWREADY,
        s_axi_BUS_A_AWADDR,
        s_axi_BUS_A_WVALID,
        s_axi_BUS_A_WREADY,
        s_axi_BUS_A_WDATA,
        s_axi_BUS_A_WSTRB,
        s_axi_BUS_A_ARVALID,
        s_axi_BUS_A_ARREADY,
        s_axi_BUS_A_ARADDR,
        s_axi_BUS_A_RVALID,
        s_axi_BUS_A_RREADY,
        s_axi_BUS_A_RDATA,
        s_axi_BUS_A_RRESP,
        s_axi_BUS_A_BVALID,
        s_axi_BUS_A_BREADY,
        s_axi_BUS_A_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;
parameter    C_S_AXI_BUS_A_DATA_WIDTH = 32;
parameter    C_S_AXI_BUS_A_ADDR_WIDTH = 20;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_BUS_A_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [31:0] saveValueLayer1_V_Addr_A;
output   saveValueLayer1_V_EN_A;
output  [3:0] saveValueLayer1_V_WEN_A;
output  [31:0] saveValueLayer1_V_Din_A;
input  [31:0] saveValueLayer1_V_Dout_A;
output   saveValueLayer1_V_Clk_A;
output   saveValueLayer1_V_Rst_A;
output  [31:0] saveValueLayer2_V_Addr_A;
output   saveValueLayer2_V_EN_A;
output  [3:0] saveValueLayer2_V_WEN_A;
output  [31:0] saveValueLayer2_V_Din_A;
input  [31:0] saveValueLayer2_V_Dout_A;
output   saveValueLayer2_V_Clk_A;
output   saveValueLayer2_V_Rst_A;
output  [31:0] saveValueLayer3_V_Addr_A;
output   saveValueLayer3_V_EN_A;
output  [3:0] saveValueLayer3_V_WEN_A;
output  [31:0] saveValueLayer3_V_Din_A;
input  [31:0] saveValueLayer3_V_Dout_A;
output   saveValueLayer3_V_Clk_A;
output   saveValueLayer3_V_Rst_A;
output  [31:0] Layer1_WeightArray_V_Addr_A;
output   Layer1_WeightArray_V_EN_A;
output  [3:0] Layer1_WeightArray_V_WEN_A;
output  [31:0] Layer1_WeightArray_V_Din_A;
input  [31:0] Layer1_WeightArray_V_Dout_A;
output   Layer1_WeightArray_V_Clk_A;
output   Layer1_WeightArray_V_Rst_A;
output  [31:0] Layer1_BiasArray_V_Addr_A;
output   Layer1_BiasArray_V_EN_A;
output  [3:0] Layer1_BiasArray_V_WEN_A;
output  [31:0] Layer1_BiasArray_V_Din_A;
input  [31:0] Layer1_BiasArray_V_Dout_A;
output   Layer1_BiasArray_V_Clk_A;
output   Layer1_BiasArray_V_Rst_A;
output  [31:0] Layer2_WeightMatrix_V_Addr_A;
output   Layer2_WeightMatrix_V_EN_A;
output  [3:0] Layer2_WeightMatrix_V_WEN_A;
output  [31:0] Layer2_WeightMatrix_V_Din_A;
input  [31:0] Layer2_WeightMatrix_V_Dout_A;
output   Layer2_WeightMatrix_V_Clk_A;
output   Layer2_WeightMatrix_V_Rst_A;
output  [31:0] Layer2_BiasArray_V_Addr_A;
output   Layer2_BiasArray_V_EN_A;
output  [3:0] Layer2_BiasArray_V_WEN_A;
output  [31:0] Layer2_BiasArray_V_Din_A;
input  [31:0] Layer2_BiasArray_V_Dout_A;
output   Layer2_BiasArray_V_Clk_A;
output   Layer2_BiasArray_V_Rst_A;
output  [31:0] Layer3_weightArray_0_V_Addr_A;
output   Layer3_weightArray_0_V_EN_A;
output  [3:0] Layer3_weightArray_0_V_WEN_A;
output  [31:0] Layer3_weightArray_0_V_Din_A;
input  [31:0] Layer3_weightArray_0_V_Dout_A;
output   Layer3_weightArray_0_V_Clk_A;
output   Layer3_weightArray_0_V_Rst_A;
output  [31:0] Layer3_weightArray_1_V_Addr_A;
output   Layer3_weightArray_1_V_EN_A;
output  [3:0] Layer3_weightArray_1_V_WEN_A;
output  [31:0] Layer3_weightArray_1_V_Din_A;
input  [31:0] Layer3_weightArray_1_V_Dout_A;
output   Layer3_weightArray_1_V_Clk_A;
output   Layer3_weightArray_1_V_Rst_A;
output  [31:0] Layer3_weightArray_2_V_Addr_A;
output   Layer3_weightArray_2_V_EN_A;
output  [3:0] Layer3_weightArray_2_V_WEN_A;
output  [31:0] Layer3_weightArray_2_V_Din_A;
input  [31:0] Layer3_weightArray_2_V_Dout_A;
output   Layer3_weightArray_2_V_Clk_A;
output   Layer3_weightArray_2_V_Rst_A;
output  [31:0] Layer3_weightArray_3_V_Addr_A;
output   Layer3_weightArray_3_V_EN_A;
output  [3:0] Layer3_weightArray_3_V_WEN_A;
output  [31:0] Layer3_weightArray_3_V_Din_A;
input  [31:0] Layer3_weightArray_3_V_Dout_A;
output   Layer3_weightArray_3_V_Clk_A;
output   Layer3_weightArray_3_V_Rst_A;
output  [31:0] Layer3_Bias_V_Addr_A;
output   Layer3_Bias_V_EN_A;
output  [3:0] Layer3_Bias_V_WEN_A;
output  [31:0] Layer3_Bias_V_Din_A;
input  [31:0] Layer3_Bias_V_Dout_A;
output   Layer3_Bias_V_Clk_A;
output   Layer3_Bias_V_Rst_A;
output  [31:0] Layer4_weightArray_V_Addr_A;
output   Layer4_weightArray_V_EN_A;
output  [3:0] Layer4_weightArray_V_WEN_A;
output  [31:0] Layer4_weightArray_V_Din_A;
input  [31:0] Layer4_weightArray_V_Dout_A;
output   Layer4_weightArray_V_Clk_A;
output   Layer4_weightArray_V_Rst_A;
output  [31:0] Layer4_Bias_V_Addr_A;
output   Layer4_Bias_V_EN_A;
output  [3:0] Layer4_Bias_V_WEN_A;
output  [31:0] Layer4_Bias_V_Din_A;
input  [31:0] Layer4_Bias_V_Dout_A;
output   Layer4_Bias_V_Clk_A;
output   Layer4_Bias_V_Rst_A;
input   s_axi_BUS_A_AWVALID;
output   s_axi_BUS_A_AWREADY;
input  [C_S_AXI_BUS_A_ADDR_WIDTH - 1:0] s_axi_BUS_A_AWADDR;
input   s_axi_BUS_A_WVALID;
output   s_axi_BUS_A_WREADY;
input  [C_S_AXI_BUS_A_DATA_WIDTH - 1:0] s_axi_BUS_A_WDATA;
input  [C_S_AXI_BUS_A_WSTRB_WIDTH - 1:0] s_axi_BUS_A_WSTRB;
input   s_axi_BUS_A_ARVALID;
output   s_axi_BUS_A_ARREADY;
input  [C_S_AXI_BUS_A_ADDR_WIDTH - 1:0] s_axi_BUS_A_ARADDR;
output   s_axi_BUS_A_RVALID;
input   s_axi_BUS_A_RREADY;
output  [C_S_AXI_BUS_A_DATA_WIDTH - 1:0] s_axi_BUS_A_RDATA;
output  [1:0] s_axi_BUS_A_RRESP;
output   s_axi_BUS_A_BVALID;
input   s_axi_BUS_A_BREADY;
output  [1:0] s_axi_BUS_A_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [7:0] Config_rep;
wire   [17:0] src_V_q0;
wire   [7:0] Config_rep_s_fu_158_p3;
reg   [7:0] Config_rep_s_reg_177;
wire   [7:0] i_1_fu_171_p2;
reg   [7:0] i_1_reg_185;
wire    ap_CS_fsm_state2;
wire   [15:0] grp_CNN_1D_fu_110_src_V_address0;
wire    grp_CNN_1D_fu_110_src_V_ce0;
wire   [17:0] grp_CNN_1D_fu_110_src_V_d0;
wire    grp_CNN_1D_fu_110_src_V_we0;
wire   [31:0] grp_CNN_1D_fu_110_saveValueLayer1_V_Addr_A;
wire    grp_CNN_1D_fu_110_saveValueLayer1_V_EN_A;
wire   [31:0] grp_CNN_1D_fu_110_saveValueLayer1_V_Din_A;
wire   [3:0] grp_CNN_1D_fu_110_saveValueLayer1_V_WEN_A;
wire   [31:0] grp_CNN_1D_fu_110_saveValueLayer2_V_Addr_A;
wire    grp_CNN_1D_fu_110_saveValueLayer2_V_EN_A;
wire   [31:0] grp_CNN_1D_fu_110_saveValueLayer2_V_Din_A;
wire   [3:0] grp_CNN_1D_fu_110_saveValueLayer2_V_WEN_A;
wire   [31:0] grp_CNN_1D_fu_110_saveValueLayer3_V_Addr_A;
wire    grp_CNN_1D_fu_110_saveValueLayer3_V_EN_A;
wire   [31:0] grp_CNN_1D_fu_110_saveValueLayer3_V_Din_A;
wire   [3:0] grp_CNN_1D_fu_110_saveValueLayer3_V_WEN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer1_WeightArray_V_Addr_A;
wire    grp_CNN_1D_fu_110_Layer1_WeightArray_V_EN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer1_WeightArray_V_Din_A;
wire   [3:0] grp_CNN_1D_fu_110_Layer1_WeightArray_V_WEN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer1_BiasArray_V_Addr_A;
wire    grp_CNN_1D_fu_110_Layer1_BiasArray_V_EN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer1_BiasArray_V_Din_A;
wire   [3:0] grp_CNN_1D_fu_110_Layer1_BiasArray_V_WEN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_Addr_A;
wire    grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_EN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_Din_A;
wire   [3:0] grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_WEN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer2_BiasArray_V_Addr_A;
wire    grp_CNN_1D_fu_110_Layer2_BiasArray_V_EN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer2_BiasArray_V_Din_A;
wire   [3:0] grp_CNN_1D_fu_110_Layer2_BiasArray_V_WEN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer3_weightArray_0_Addr_A;
wire    grp_CNN_1D_fu_110_Layer3_weightArray_0_EN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer3_weightArray_0_Din_A;
wire   [3:0] grp_CNN_1D_fu_110_Layer3_weightArray_0_WEN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer3_weightArray_1_Addr_A;
wire    grp_CNN_1D_fu_110_Layer3_weightArray_1_EN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer3_weightArray_1_Din_A;
wire   [3:0] grp_CNN_1D_fu_110_Layer3_weightArray_1_WEN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer3_weightArray_2_Addr_A;
wire    grp_CNN_1D_fu_110_Layer3_weightArray_2_EN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer3_weightArray_2_Din_A;
wire   [3:0] grp_CNN_1D_fu_110_Layer3_weightArray_2_WEN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer3_weightArray_3_Addr_A;
wire    grp_CNN_1D_fu_110_Layer3_weightArray_3_EN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer3_weightArray_3_Din_A;
wire   [3:0] grp_CNN_1D_fu_110_Layer3_weightArray_3_WEN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer3_Bias_V_Addr_A;
wire    grp_CNN_1D_fu_110_Layer3_Bias_V_EN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer3_Bias_V_Din_A;
wire   [3:0] grp_CNN_1D_fu_110_Layer3_Bias_V_WEN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer4_weightArray_V_Addr_A;
wire    grp_CNN_1D_fu_110_Layer4_weightArray_V_EN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer4_weightArray_V_Din_A;
wire   [3:0] grp_CNN_1D_fu_110_Layer4_weightArray_V_WEN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer4_Bias_V_Addr_A;
wire    grp_CNN_1D_fu_110_Layer4_Bias_V_EN_A;
wire   [31:0] grp_CNN_1D_fu_110_Layer4_Bias_V_Din_A;
wire   [3:0] grp_CNN_1D_fu_110_Layer4_Bias_V_WEN_A;
wire   [9:0] grp_CNN_1D_fu_110_dst_V_address0;
wire    grp_CNN_1D_fu_110_dst_V_ce0;
wire   [15:0] grp_CNN_1D_fu_110_dst_V_d0;
wire    grp_CNN_1D_fu_110_dst_V_we0;
wire    grp_CNN_1D_fu_110_ap_done;
wire    grp_CNN_1D_fu_110_ap_start;
wire    grp_CNN_1D_fu_110_ap_ready;
wire    grp_CNN_1D_fu_110_ap_idle;
reg    grp_CNN_1D_fu_110_ap_continue;
reg   [7:0] i_reg_98;
wire    ap_CS_fsm_state3;
reg    ap_reg_grp_CNN_1D_fu_110_ap_start;
wire   [0:0] exitcond_fu_166_p2;
reg    ap_sync_reg_grp_CNN_1D_fu_110_ap_ready;
reg    ap_sync_grp_CNN_1D_fu_110_ap_ready;
wire   [0:0] tmp_fu_152_p2;
reg   [2:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_reg_grp_CNN_1D_fu_110_ap_start = 1'b0;
#0 ap_sync_reg_grp_CNN_1D_fu_110_ap_ready = 1'b0;
end

MASTER_CNN_BUS_A_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_BUS_A_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_BUS_A_DATA_WIDTH ))
MASTER_CNN_BUS_A_s_axi_U(
    .AWVALID(s_axi_BUS_A_AWVALID),
    .AWREADY(s_axi_BUS_A_AWREADY),
    .AWADDR(s_axi_BUS_A_AWADDR),
    .WVALID(s_axi_BUS_A_WVALID),
    .WREADY(s_axi_BUS_A_WREADY),
    .WDATA(s_axi_BUS_A_WDATA),
    .WSTRB(s_axi_BUS_A_WSTRB),
    .ARVALID(s_axi_BUS_A_ARVALID),
    .ARREADY(s_axi_BUS_A_ARREADY),
    .ARADDR(s_axi_BUS_A_ARADDR),
    .RVALID(s_axi_BUS_A_RVALID),
    .RREADY(s_axi_BUS_A_RREADY),
    .RDATA(s_axi_BUS_A_RDATA),
    .RRESP(s_axi_BUS_A_RRESP),
    .BVALID(s_axi_BUS_A_BVALID),
    .BREADY(s_axi_BUS_A_BREADY),
    .BRESP(s_axi_BUS_A_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .Config_rep(Config_rep),
    .src_V_address0(grp_CNN_1D_fu_110_src_V_address0),
    .src_V_ce0(grp_CNN_1D_fu_110_src_V_ce0),
    .src_V_q0(src_V_q0),
    .dst_V_address0(grp_CNN_1D_fu_110_dst_V_address0),
    .dst_V_ce0(grp_CNN_1D_fu_110_dst_V_ce0),
    .dst_V_we0(grp_CNN_1D_fu_110_dst_V_we0),
    .dst_V_d0(grp_CNN_1D_fu_110_dst_V_d0)
);

CNN_1D grp_CNN_1D_fu_110(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .src_V_address0(grp_CNN_1D_fu_110_src_V_address0),
    .src_V_ce0(grp_CNN_1D_fu_110_src_V_ce0),
    .src_V_d0(grp_CNN_1D_fu_110_src_V_d0),
    .src_V_q0(src_V_q0),
    .src_V_we0(grp_CNN_1D_fu_110_src_V_we0),
    .src_V_offset(i_reg_98),
    .saveValueLayer1_V_Addr_A(grp_CNN_1D_fu_110_saveValueLayer1_V_Addr_A),
    .saveValueLayer1_V_EN_A(grp_CNN_1D_fu_110_saveValueLayer1_V_EN_A),
    .saveValueLayer1_V_Din_A(grp_CNN_1D_fu_110_saveValueLayer1_V_Din_A),
    .saveValueLayer1_V_Dout_A(32'd0),
    .saveValueLayer1_V_WEN_A(grp_CNN_1D_fu_110_saveValueLayer1_V_WEN_A),
    .saveValueLayer2_V_Addr_A(grp_CNN_1D_fu_110_saveValueLayer2_V_Addr_A),
    .saveValueLayer2_V_EN_A(grp_CNN_1D_fu_110_saveValueLayer2_V_EN_A),
    .saveValueLayer2_V_Din_A(grp_CNN_1D_fu_110_saveValueLayer2_V_Din_A),
    .saveValueLayer2_V_Dout_A(32'd0),
    .saveValueLayer2_V_WEN_A(grp_CNN_1D_fu_110_saveValueLayer2_V_WEN_A),
    .saveValueLayer3_V_Addr_A(grp_CNN_1D_fu_110_saveValueLayer3_V_Addr_A),
    .saveValueLayer3_V_EN_A(grp_CNN_1D_fu_110_saveValueLayer3_V_EN_A),
    .saveValueLayer3_V_Din_A(grp_CNN_1D_fu_110_saveValueLayer3_V_Din_A),
    .saveValueLayer3_V_Dout_A(32'd0),
    .saveValueLayer3_V_WEN_A(grp_CNN_1D_fu_110_saveValueLayer3_V_WEN_A),
    .Layer1_WeightArray_V_Addr_A(grp_CNN_1D_fu_110_Layer1_WeightArray_V_Addr_A),
    .Layer1_WeightArray_V_EN_A(grp_CNN_1D_fu_110_Layer1_WeightArray_V_EN_A),
    .Layer1_WeightArray_V_Din_A(grp_CNN_1D_fu_110_Layer1_WeightArray_V_Din_A),
    .Layer1_WeightArray_V_Dout_A(Layer1_WeightArray_V_Dout_A),
    .Layer1_WeightArray_V_WEN_A(grp_CNN_1D_fu_110_Layer1_WeightArray_V_WEN_A),
    .Layer1_BiasArray_V_Addr_A(grp_CNN_1D_fu_110_Layer1_BiasArray_V_Addr_A),
    .Layer1_BiasArray_V_EN_A(grp_CNN_1D_fu_110_Layer1_BiasArray_V_EN_A),
    .Layer1_BiasArray_V_Din_A(grp_CNN_1D_fu_110_Layer1_BiasArray_V_Din_A),
    .Layer1_BiasArray_V_Dout_A(Layer1_BiasArray_V_Dout_A),
    .Layer1_BiasArray_V_WEN_A(grp_CNN_1D_fu_110_Layer1_BiasArray_V_WEN_A),
    .Layer2_WeightMatrix_s_Addr_A(grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_Addr_A),
    .Layer2_WeightMatrix_s_EN_A(grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_EN_A),
    .Layer2_WeightMatrix_s_Din_A(grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_Din_A),
    .Layer2_WeightMatrix_s_Dout_A(Layer2_WeightMatrix_V_Dout_A),
    .Layer2_WeightMatrix_s_WEN_A(grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_WEN_A),
    .Layer2_BiasArray_V_Addr_A(grp_CNN_1D_fu_110_Layer2_BiasArray_V_Addr_A),
    .Layer2_BiasArray_V_EN_A(grp_CNN_1D_fu_110_Layer2_BiasArray_V_EN_A),
    .Layer2_BiasArray_V_Din_A(grp_CNN_1D_fu_110_Layer2_BiasArray_V_Din_A),
    .Layer2_BiasArray_V_Dout_A(Layer2_BiasArray_V_Dout_A),
    .Layer2_BiasArray_V_WEN_A(grp_CNN_1D_fu_110_Layer2_BiasArray_V_WEN_A),
    .Layer3_weightArray_0_Addr_A(grp_CNN_1D_fu_110_Layer3_weightArray_0_Addr_A),
    .Layer3_weightArray_0_EN_A(grp_CNN_1D_fu_110_Layer3_weightArray_0_EN_A),
    .Layer3_weightArray_0_Din_A(grp_CNN_1D_fu_110_Layer3_weightArray_0_Din_A),
    .Layer3_weightArray_0_Dout_A(Layer3_weightArray_0_V_Dout_A),
    .Layer3_weightArray_0_WEN_A(grp_CNN_1D_fu_110_Layer3_weightArray_0_WEN_A),
    .Layer3_weightArray_1_Addr_A(grp_CNN_1D_fu_110_Layer3_weightArray_1_Addr_A),
    .Layer3_weightArray_1_EN_A(grp_CNN_1D_fu_110_Layer3_weightArray_1_EN_A),
    .Layer3_weightArray_1_Din_A(grp_CNN_1D_fu_110_Layer3_weightArray_1_Din_A),
    .Layer3_weightArray_1_Dout_A(Layer3_weightArray_1_V_Dout_A),
    .Layer3_weightArray_1_WEN_A(grp_CNN_1D_fu_110_Layer3_weightArray_1_WEN_A),
    .Layer3_weightArray_2_Addr_A(grp_CNN_1D_fu_110_Layer3_weightArray_2_Addr_A),
    .Layer3_weightArray_2_EN_A(grp_CNN_1D_fu_110_Layer3_weightArray_2_EN_A),
    .Layer3_weightArray_2_Din_A(grp_CNN_1D_fu_110_Layer3_weightArray_2_Din_A),
    .Layer3_weightArray_2_Dout_A(Layer3_weightArray_2_V_Dout_A),
    .Layer3_weightArray_2_WEN_A(grp_CNN_1D_fu_110_Layer3_weightArray_2_WEN_A),
    .Layer3_weightArray_3_Addr_A(grp_CNN_1D_fu_110_Layer3_weightArray_3_Addr_A),
    .Layer3_weightArray_3_EN_A(grp_CNN_1D_fu_110_Layer3_weightArray_3_EN_A),
    .Layer3_weightArray_3_Din_A(grp_CNN_1D_fu_110_Layer3_weightArray_3_Din_A),
    .Layer3_weightArray_3_Dout_A(Layer3_weightArray_3_V_Dout_A),
    .Layer3_weightArray_3_WEN_A(grp_CNN_1D_fu_110_Layer3_weightArray_3_WEN_A),
    .Layer3_Bias_V_Addr_A(grp_CNN_1D_fu_110_Layer3_Bias_V_Addr_A),
    .Layer3_Bias_V_EN_A(grp_CNN_1D_fu_110_Layer3_Bias_V_EN_A),
    .Layer3_Bias_V_Din_A(grp_CNN_1D_fu_110_Layer3_Bias_V_Din_A),
    .Layer3_Bias_V_Dout_A(Layer3_Bias_V_Dout_A),
    .Layer3_Bias_V_WEN_A(grp_CNN_1D_fu_110_Layer3_Bias_V_WEN_A),
    .Layer4_weightArray_V_Addr_A(grp_CNN_1D_fu_110_Layer4_weightArray_V_Addr_A),
    .Layer4_weightArray_V_EN_A(grp_CNN_1D_fu_110_Layer4_weightArray_V_EN_A),
    .Layer4_weightArray_V_Din_A(grp_CNN_1D_fu_110_Layer4_weightArray_V_Din_A),
    .Layer4_weightArray_V_Dout_A(Layer4_weightArray_V_Dout_A),
    .Layer4_weightArray_V_WEN_A(grp_CNN_1D_fu_110_Layer4_weightArray_V_WEN_A),
    .Layer4_Bias_V_Addr_A(grp_CNN_1D_fu_110_Layer4_Bias_V_Addr_A),
    .Layer4_Bias_V_EN_A(grp_CNN_1D_fu_110_Layer4_Bias_V_EN_A),
    .Layer4_Bias_V_Din_A(grp_CNN_1D_fu_110_Layer4_Bias_V_Din_A),
    .Layer4_Bias_V_Dout_A(Layer4_Bias_V_Dout_A),
    .Layer4_Bias_V_WEN_A(grp_CNN_1D_fu_110_Layer4_Bias_V_WEN_A),
    .dst_V_address0(grp_CNN_1D_fu_110_dst_V_address0),
    .dst_V_ce0(grp_CNN_1D_fu_110_dst_V_ce0),
    .dst_V_d0(grp_CNN_1D_fu_110_dst_V_d0),
    .dst_V_q0(16'd0),
    .dst_V_we0(grp_CNN_1D_fu_110_dst_V_we0),
    .src_V_offset_ap_vld(1'b1),
    .ap_done(grp_CNN_1D_fu_110_ap_done),
    .ap_start(grp_CNN_1D_fu_110_ap_start),
    .ap_ready(grp_CNN_1D_fu_110_ap_ready),
    .ap_idle(grp_CNN_1D_fu_110_ap_idle),
    .ap_continue(grp_CNN_1D_fu_110_ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_grp_CNN_1D_fu_110_ap_start <= 1'b0;
    end else begin
        if ((((ap_sync_grp_CNN_1D_fu_110_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state3)) | ((exitcond_fu_166_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
            ap_reg_grp_CNN_1D_fu_110_ap_start <= 1'b1;
        end else if ((grp_CNN_1D_fu_110_ap_ready == 1'b1)) begin
            ap_reg_grp_CNN_1D_fu_110_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_CNN_1D_fu_110_ap_ready <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            if ((grp_CNN_1D_fu_110_ap_done == 1'b1)) begin
                ap_sync_reg_grp_CNN_1D_fu_110_ap_ready <= 1'b0;
            end else if ((grp_CNN_1D_fu_110_ap_ready == 1'b1)) begin
                ap_sync_reg_grp_CNN_1D_fu_110_ap_ready <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_CNN_1D_fu_110_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_98 <= i_1_reg_185;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_98 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        Config_rep_s_reg_177 <= Config_rep_s_fu_158_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_185 <= i_1_fu_171_p2;
    end
end

always @ (*) begin
    if (((exitcond_fu_166_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_fu_166_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_sync_reg_grp_CNN_1D_fu_110_ap_ready == 1'b0)) begin
        ap_sync_grp_CNN_1D_fu_110_ap_ready = grp_CNN_1D_fu_110_ap_ready;
    end else begin
        ap_sync_grp_CNN_1D_fu_110_ap_ready = 1'b1;
    end
end

always @ (*) begin
    if (((grp_CNN_1D_fu_110_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        grp_CNN_1D_fu_110_ap_continue = 1'b1;
    end else begin
        grp_CNN_1D_fu_110_ap_continue = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond_fu_166_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_CNN_1D_fu_110_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Config_rep_s_fu_158_p3 = ((tmp_fu_152_p2[0:0] === 1'b1) ? Config_rep : 8'd200);

assign Layer1_BiasArray_V_Addr_A = grp_CNN_1D_fu_110_Layer1_BiasArray_V_Addr_A;

assign Layer1_BiasArray_V_Clk_A = ap_clk;

assign Layer1_BiasArray_V_Din_A = 32'd0;

assign Layer1_BiasArray_V_EN_A = grp_CNN_1D_fu_110_Layer1_BiasArray_V_EN_A;

assign Layer1_BiasArray_V_Rst_A = ap_rst_n_inv;

assign Layer1_BiasArray_V_WEN_A = 4'd0;

assign Layer1_WeightArray_V_Addr_A = grp_CNN_1D_fu_110_Layer1_WeightArray_V_Addr_A;

assign Layer1_WeightArray_V_Clk_A = ap_clk;

assign Layer1_WeightArray_V_Din_A = 32'd0;

assign Layer1_WeightArray_V_EN_A = grp_CNN_1D_fu_110_Layer1_WeightArray_V_EN_A;

assign Layer1_WeightArray_V_Rst_A = ap_rst_n_inv;

assign Layer1_WeightArray_V_WEN_A = 4'd0;

assign Layer2_BiasArray_V_Addr_A = grp_CNN_1D_fu_110_Layer2_BiasArray_V_Addr_A;

assign Layer2_BiasArray_V_Clk_A = ap_clk;

assign Layer2_BiasArray_V_Din_A = 32'd0;

assign Layer2_BiasArray_V_EN_A = grp_CNN_1D_fu_110_Layer2_BiasArray_V_EN_A;

assign Layer2_BiasArray_V_Rst_A = ap_rst_n_inv;

assign Layer2_BiasArray_V_WEN_A = 4'd0;

assign Layer2_WeightMatrix_V_Addr_A = grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_Addr_A;

assign Layer2_WeightMatrix_V_Clk_A = ap_clk;

assign Layer2_WeightMatrix_V_Din_A = 32'd0;

assign Layer2_WeightMatrix_V_EN_A = grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_EN_A;

assign Layer2_WeightMatrix_V_Rst_A = ap_rst_n_inv;

assign Layer2_WeightMatrix_V_WEN_A = 4'd0;

assign Layer3_Bias_V_Addr_A = grp_CNN_1D_fu_110_Layer3_Bias_V_Addr_A;

assign Layer3_Bias_V_Clk_A = ap_clk;

assign Layer3_Bias_V_Din_A = 32'd0;

assign Layer3_Bias_V_EN_A = grp_CNN_1D_fu_110_Layer3_Bias_V_EN_A;

assign Layer3_Bias_V_Rst_A = ap_rst_n_inv;

assign Layer3_Bias_V_WEN_A = 4'd0;

assign Layer3_weightArray_0_V_Addr_A = grp_CNN_1D_fu_110_Layer3_weightArray_0_Addr_A;

assign Layer3_weightArray_0_V_Clk_A = ap_clk;

assign Layer3_weightArray_0_V_Din_A = 32'd0;

assign Layer3_weightArray_0_V_EN_A = grp_CNN_1D_fu_110_Layer3_weightArray_0_EN_A;

assign Layer3_weightArray_0_V_Rst_A = ap_rst_n_inv;

assign Layer3_weightArray_0_V_WEN_A = 4'd0;

assign Layer3_weightArray_1_V_Addr_A = grp_CNN_1D_fu_110_Layer3_weightArray_1_Addr_A;

assign Layer3_weightArray_1_V_Clk_A = ap_clk;

assign Layer3_weightArray_1_V_Din_A = 32'd0;

assign Layer3_weightArray_1_V_EN_A = grp_CNN_1D_fu_110_Layer3_weightArray_1_EN_A;

assign Layer3_weightArray_1_V_Rst_A = ap_rst_n_inv;

assign Layer3_weightArray_1_V_WEN_A = 4'd0;

assign Layer3_weightArray_2_V_Addr_A = grp_CNN_1D_fu_110_Layer3_weightArray_2_Addr_A;

assign Layer3_weightArray_2_V_Clk_A = ap_clk;

assign Layer3_weightArray_2_V_Din_A = 32'd0;

assign Layer3_weightArray_2_V_EN_A = grp_CNN_1D_fu_110_Layer3_weightArray_2_EN_A;

assign Layer3_weightArray_2_V_Rst_A = ap_rst_n_inv;

assign Layer3_weightArray_2_V_WEN_A = 4'd0;

assign Layer3_weightArray_3_V_Addr_A = grp_CNN_1D_fu_110_Layer3_weightArray_3_Addr_A;

assign Layer3_weightArray_3_V_Clk_A = ap_clk;

assign Layer3_weightArray_3_V_Din_A = 32'd0;

assign Layer3_weightArray_3_V_EN_A = grp_CNN_1D_fu_110_Layer3_weightArray_3_EN_A;

assign Layer3_weightArray_3_V_Rst_A = ap_rst_n_inv;

assign Layer3_weightArray_3_V_WEN_A = 4'd0;

assign Layer4_Bias_V_Addr_A = grp_CNN_1D_fu_110_Layer4_Bias_V_Addr_A;

assign Layer4_Bias_V_Clk_A = ap_clk;

assign Layer4_Bias_V_Din_A = 32'd0;

assign Layer4_Bias_V_EN_A = grp_CNN_1D_fu_110_Layer4_Bias_V_EN_A;

assign Layer4_Bias_V_Rst_A = ap_rst_n_inv;

assign Layer4_Bias_V_WEN_A = 4'd0;

assign Layer4_weightArray_V_Addr_A = grp_CNN_1D_fu_110_Layer4_weightArray_V_Addr_A;

assign Layer4_weightArray_V_Clk_A = ap_clk;

assign Layer4_weightArray_V_Din_A = 32'd0;

assign Layer4_weightArray_V_EN_A = grp_CNN_1D_fu_110_Layer4_weightArray_V_EN_A;

assign Layer4_weightArray_V_Rst_A = ap_rst_n_inv;

assign Layer4_weightArray_V_WEN_A = 4'd0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign exitcond_fu_166_p2 = ((i_reg_98 == Config_rep_s_reg_177) ? 1'b1 : 1'b0);

assign grp_CNN_1D_fu_110_ap_start = ap_reg_grp_CNN_1D_fu_110_ap_start;

assign i_1_fu_171_p2 = (i_reg_98 + 8'd1);

assign saveValueLayer1_V_Addr_A = grp_CNN_1D_fu_110_saveValueLayer1_V_Addr_A;

assign saveValueLayer1_V_Clk_A = ap_clk;

assign saveValueLayer1_V_Din_A = grp_CNN_1D_fu_110_saveValueLayer1_V_Din_A;

assign saveValueLayer1_V_EN_A = grp_CNN_1D_fu_110_saveValueLayer1_V_EN_A;

assign saveValueLayer1_V_Rst_A = ap_rst_n_inv;

assign saveValueLayer1_V_WEN_A = grp_CNN_1D_fu_110_saveValueLayer1_V_WEN_A;

assign saveValueLayer2_V_Addr_A = grp_CNN_1D_fu_110_saveValueLayer2_V_Addr_A;

assign saveValueLayer2_V_Clk_A = ap_clk;

assign saveValueLayer2_V_Din_A = grp_CNN_1D_fu_110_saveValueLayer2_V_Din_A;

assign saveValueLayer2_V_EN_A = grp_CNN_1D_fu_110_saveValueLayer2_V_EN_A;

assign saveValueLayer2_V_Rst_A = ap_rst_n_inv;

assign saveValueLayer2_V_WEN_A = grp_CNN_1D_fu_110_saveValueLayer2_V_WEN_A;

assign saveValueLayer3_V_Addr_A = grp_CNN_1D_fu_110_saveValueLayer3_V_Addr_A;

assign saveValueLayer3_V_Clk_A = ap_clk;

assign saveValueLayer3_V_Din_A = grp_CNN_1D_fu_110_saveValueLayer3_V_Din_A;

assign saveValueLayer3_V_EN_A = grp_CNN_1D_fu_110_saveValueLayer3_V_EN_A;

assign saveValueLayer3_V_Rst_A = ap_rst_n_inv;

assign saveValueLayer3_V_WEN_A = grp_CNN_1D_fu_110_saveValueLayer3_V_WEN_A;

assign tmp_fu_152_p2 = ((Config_rep < 8'd200) ? 1'b1 : 1'b0);

endmodule //MASTER_CNN
