lappend pragmaStatus0 {pragma "PIPELINE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "Layer1_Conv1D/Convolution_Loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "INLINE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "mult" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'mult' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "UNROLL" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "Layer1_Conv/fill_Filters" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'fill_Filters' does not exist in function 'Layer1_Conv'. "}
lappend pragmaStatus3 {pragma "UNROLL" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "Layer3_Dense/Loop_Mult_inner" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "UNROLL" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "Layer4_Dense/Loop_DST" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "INTERFACE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "dst" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'dst' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K1"}
lappend pragmaStatus7 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K2"}
lappend pragmaStatus8 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K0"}
lappend pragmaStatus9 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'first_order_fixed_16::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "first_order_fixed_16::sin_cos_K1"}
lappend pragmaStatus10 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K0"}
lappend pragmaStatus11 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K2"}
lappend pragmaStatus12 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K2"}
lappend pragmaStatus13 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K1"}
lappend pragmaStatus14 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K1"}
lappend pragmaStatus15 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K3' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K3"}
lappend pragmaStatus16 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K3' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K3"}
lappend pragmaStatus17 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K4' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K4"}
lappend pragmaStatus18 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K0"}
lappend pragmaStatus19 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K1"}
lappend pragmaStatus20 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K1"}
lappend pragmaStatus21 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K1"}
lappend pragmaStatus22 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K4' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K4"}
lappend pragmaStatus23 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K4' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K4"}
lappend pragmaStatus24 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'first_order_fixed_16::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "first_order_fixed_16::sin_cos_K0"}
lappend pragmaStatus25 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K0"}
lappend pragmaStatus26 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K2"}
lappend pragmaStatus27 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K0"}
lappend pragmaStatus28 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K2"}
lappend pragmaStatus29 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K2"}
lappend pragmaStatus30 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K0"}
lappend pragmaStatus31 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/1_keras.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K3' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K3"}
lappend pragmaStatus0 {pragma "PIPELINE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "Layer1_Conv1D/Convolution_Loop" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'Layer1_Conv1D' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "INLINE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "mult" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'mult' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "UNROLL" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "Layer1_Conv/fill_Filters" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'Layer1_Conv' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "UNROLL" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "Layer3_Dense/Loop_Mult_inner" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'Layer3_Dense' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "UNROLL" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "Layer4_Dense/Loop_DST" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Function 'Layer4_Dense' does not exist in any synthesis source file."}
lappend pragmaStatus5 {pragma "INTERFACE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "dst" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'dst' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K4' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K4"}
lappend pragmaStatus7 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K1"}
lappend pragmaStatus8 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K3' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K3"}
lappend pragmaStatus9 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K0"}
lappend pragmaStatus10 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K2"}
lappend pragmaStatus11 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K2"}
lappend pragmaStatus12 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K0"}
lappend pragmaStatus13 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K4' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K4"}
lappend pragmaStatus14 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K2"}
lappend pragmaStatus15 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K3' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K3"}
lappend pragmaStatus16 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K0"}
lappend pragmaStatus17 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K1"}
lappend pragmaStatus18 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'first_order_fixed_16::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "first_order_fixed_16::sin_cos_K1"}
lappend pragmaStatus19 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K1"}
lappend pragmaStatus20 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K3' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K3"}
lappend pragmaStatus21 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K4' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K4"}
lappend pragmaStatus22 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K1"}
lappend pragmaStatus23 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K0"}
lappend pragmaStatus24 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K0"}
lappend pragmaStatus25 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'first_order_fixed_16::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "first_order_fixed_16::sin_cos_K0"}
lappend pragmaStatus26 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K2"}
lappend pragmaStatus27 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K1"}
lappend pragmaStatus28 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K2"}
lappend pragmaStatus29 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K0"}
lappend pragmaStatus30 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K2"}
lappend pragmaStatus31 {pragma "RESOURCE" source "D:/HLS/After_ICDD/ForVivado_NUEVOSPESOS/MergeringBRAM/SRC/2_Manage_CNN.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K1"}
