// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// BUS_A
// 0x00000 : Control signals
//           bit 0  - ap_start (Read/Write/COH)
//           bit 1  - ap_done (Read/COR)
//           bit 2  - ap_idle (Read)
//           bit 3  - ap_ready (Read)
//           bit 7  - auto_restart (Read/Write)
//           others - reserved
// 0x00004 : Global Interrupt Enable Register
//           bit 0  - Global Interrupt Enable (Read/Write)
//           others - reserved
// 0x00008 : IP Interrupt Enable Register (Read/Write)
//           bit 0  - Channel 0 (ap_done)
//           bit 1  - Channel 1 (ap_ready)
//           others - reserved
// 0x0000c : IP Interrupt Status Register (Read/TOW)
//           bit 0  - Channel 0 (ap_done)
//           bit 1  - Channel 1 (ap_ready)
//           others - reserved
// 0x00010 : Data signal of Config_rep
//           bit 7~0 - Config_rep[7:0] (Read/Write)
//           others  - reserved
// 0x00014 : reserved
// 0x40000 ~
// 0x7ffff : Memory 'src_V' (38400 * 18b)
//           Word n : bit [17:0] - src_V[n]
//                    others     - reserved
// 0x80000 ~
// 0x807ff : Memory 'dst_V' (600 * 16b)
//           Word n : bit [15: 0] - dst_V[2n]
//                    bit [31:16] - dst_V[2n+1]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XMASTER_CNN_BUS_A_ADDR_AP_CTRL         0x00000
#define XMASTER_CNN_BUS_A_ADDR_GIE             0x00004
#define XMASTER_CNN_BUS_A_ADDR_IER             0x00008
#define XMASTER_CNN_BUS_A_ADDR_ISR             0x0000c
#define XMASTER_CNN_BUS_A_ADDR_CONFIG_REP_DATA 0x00010
#define XMASTER_CNN_BUS_A_BITS_CONFIG_REP_DATA 8
#define XMASTER_CNN_BUS_A_ADDR_SRC_V_BASE      0x40000
#define XMASTER_CNN_BUS_A_ADDR_SRC_V_HIGH      0x7ffff
#define XMASTER_CNN_BUS_A_WIDTH_SRC_V          18
#define XMASTER_CNN_BUS_A_DEPTH_SRC_V          38400
#define XMASTER_CNN_BUS_A_ADDR_DST_V_BASE      0x80000
#define XMASTER_CNN_BUS_A_ADDR_DST_V_HIGH      0x807ff
#define XMASTER_CNN_BUS_A_WIDTH_DST_V          16
#define XMASTER_CNN_BUS_A_DEPTH_DST_V          600

