-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MASTER_CNN is
generic (
    C_S_AXI_BUS_A_ADDR_WIDTH : INTEGER := 20;
    C_S_AXI_BUS_A_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    saveValueLayer1_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    saveValueLayer1_V_EN_A : OUT STD_LOGIC;
    saveValueLayer1_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    saveValueLayer1_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    saveValueLayer1_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    saveValueLayer1_V_Clk_A : OUT STD_LOGIC;
    saveValueLayer1_V_Rst_A : OUT STD_LOGIC;
    saveValueLayer2_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    saveValueLayer2_V_EN_A : OUT STD_LOGIC;
    saveValueLayer2_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    saveValueLayer2_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    saveValueLayer2_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    saveValueLayer2_V_Clk_A : OUT STD_LOGIC;
    saveValueLayer2_V_Rst_A : OUT STD_LOGIC;
    saveValueLayer3_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    saveValueLayer3_V_EN_A : OUT STD_LOGIC;
    saveValueLayer3_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    saveValueLayer3_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    saveValueLayer3_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    saveValueLayer3_V_Clk_A : OUT STD_LOGIC;
    saveValueLayer3_V_Rst_A : OUT STD_LOGIC;
    Layer1_WeightArray_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer1_WeightArray_V_EN_A : OUT STD_LOGIC;
    Layer1_WeightArray_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    Layer1_WeightArray_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer1_WeightArray_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    Layer1_WeightArray_V_Clk_A : OUT STD_LOGIC;
    Layer1_WeightArray_V_Rst_A : OUT STD_LOGIC;
    Layer1_BiasArray_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer1_BiasArray_V_EN_A : OUT STD_LOGIC;
    Layer1_BiasArray_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    Layer1_BiasArray_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer1_BiasArray_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    Layer1_BiasArray_V_Clk_A : OUT STD_LOGIC;
    Layer1_BiasArray_V_Rst_A : OUT STD_LOGIC;
    Layer2_WeightMatrix_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer2_WeightMatrix_V_EN_A : OUT STD_LOGIC;
    Layer2_WeightMatrix_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    Layer2_WeightMatrix_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer2_WeightMatrix_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    Layer2_WeightMatrix_V_Clk_A : OUT STD_LOGIC;
    Layer2_WeightMatrix_V_Rst_A : OUT STD_LOGIC;
    Layer2_BiasArray_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer2_BiasArray_V_EN_A : OUT STD_LOGIC;
    Layer2_BiasArray_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    Layer2_BiasArray_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer2_BiasArray_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    Layer2_BiasArray_V_Clk_A : OUT STD_LOGIC;
    Layer2_BiasArray_V_Rst_A : OUT STD_LOGIC;
    Layer3_weightArray_0_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer3_weightArray_0_V_EN_A : OUT STD_LOGIC;
    Layer3_weightArray_0_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    Layer3_weightArray_0_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer3_weightArray_0_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    Layer3_weightArray_0_V_Clk_A : OUT STD_LOGIC;
    Layer3_weightArray_0_V_Rst_A : OUT STD_LOGIC;
    Layer3_weightArray_1_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer3_weightArray_1_V_EN_A : OUT STD_LOGIC;
    Layer3_weightArray_1_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    Layer3_weightArray_1_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer3_weightArray_1_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    Layer3_weightArray_1_V_Clk_A : OUT STD_LOGIC;
    Layer3_weightArray_1_V_Rst_A : OUT STD_LOGIC;
    Layer3_weightArray_2_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer3_weightArray_2_V_EN_A : OUT STD_LOGIC;
    Layer3_weightArray_2_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    Layer3_weightArray_2_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer3_weightArray_2_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    Layer3_weightArray_2_V_Clk_A : OUT STD_LOGIC;
    Layer3_weightArray_2_V_Rst_A : OUT STD_LOGIC;
    Layer3_weightArray_3_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer3_weightArray_3_V_EN_A : OUT STD_LOGIC;
    Layer3_weightArray_3_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    Layer3_weightArray_3_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer3_weightArray_3_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    Layer3_weightArray_3_V_Clk_A : OUT STD_LOGIC;
    Layer3_weightArray_3_V_Rst_A : OUT STD_LOGIC;
    Layer3_Bias_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer3_Bias_V_EN_A : OUT STD_LOGIC;
    Layer3_Bias_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    Layer3_Bias_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer3_Bias_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    Layer3_Bias_V_Clk_A : OUT STD_LOGIC;
    Layer3_Bias_V_Rst_A : OUT STD_LOGIC;
    Layer4_weightArray_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer4_weightArray_V_EN_A : OUT STD_LOGIC;
    Layer4_weightArray_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    Layer4_weightArray_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer4_weightArray_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    Layer4_weightArray_V_Clk_A : OUT STD_LOGIC;
    Layer4_weightArray_V_Rst_A : OUT STD_LOGIC;
    Layer4_Bias_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer4_Bias_V_EN_A : OUT STD_LOGIC;
    Layer4_Bias_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    Layer4_Bias_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    Layer4_Bias_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    Layer4_Bias_V_Clk_A : OUT STD_LOGIC;
    Layer4_Bias_V_Rst_A : OUT STD_LOGIC;
    s_axi_BUS_A_AWVALID : IN STD_LOGIC;
    s_axi_BUS_A_AWREADY : OUT STD_LOGIC;
    s_axi_BUS_A_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_ADDR_WIDTH-1 downto 0);
    s_axi_BUS_A_WVALID : IN STD_LOGIC;
    s_axi_BUS_A_WREADY : OUT STD_LOGIC;
    s_axi_BUS_A_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_DATA_WIDTH-1 downto 0);
    s_axi_BUS_A_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_DATA_WIDTH/8-1 downto 0);
    s_axi_BUS_A_ARVALID : IN STD_LOGIC;
    s_axi_BUS_A_ARREADY : OUT STD_LOGIC;
    s_axi_BUS_A_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_ADDR_WIDTH-1 downto 0);
    s_axi_BUS_A_RVALID : OUT STD_LOGIC;
    s_axi_BUS_A_RREADY : IN STD_LOGIC;
    s_axi_BUS_A_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_BUS_A_DATA_WIDTH-1 downto 0);
    s_axi_BUS_A_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_BUS_A_BVALID : OUT STD_LOGIC;
    s_axi_BUS_A_BREADY : IN STD_LOGIC;
    s_axi_BUS_A_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of MASTER_CNN is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "MASTER_CNN,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.400000,HLS_SYN_LAT=378001,HLS_SYN_TPT=none,HLS_SYN_MEM=280,HLS_SYN_DSP=199,HLS_SYN_FF=35024,HLS_SYN_LUT=37287}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_C8 : STD_LOGIC_VECTOR (7 downto 0) := "11001000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal Config_rep : STD_LOGIC_VECTOR (7 downto 0);
    signal src_V_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal Config_rep_s_fu_158_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal Config_rep_s_reg_177 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_1_fu_171_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_1_reg_185 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_CNN_1D_fu_110_src_V_address0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_CNN_1D_fu_110_src_V_ce0 : STD_LOGIC;
    signal grp_CNN_1D_fu_110_src_V_d0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_CNN_1D_fu_110_src_V_we0 : STD_LOGIC;
    signal grp_CNN_1D_fu_110_saveValueLayer1_V_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_saveValueLayer1_V_EN_A : STD_LOGIC;
    signal grp_CNN_1D_fu_110_saveValueLayer1_V_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_saveValueLayer1_V_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_CNN_1D_fu_110_saveValueLayer2_V_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_saveValueLayer2_V_EN_A : STD_LOGIC;
    signal grp_CNN_1D_fu_110_saveValueLayer2_V_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_saveValueLayer2_V_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_CNN_1D_fu_110_saveValueLayer3_V_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_saveValueLayer3_V_EN_A : STD_LOGIC;
    signal grp_CNN_1D_fu_110_saveValueLayer3_V_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_saveValueLayer3_V_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_CNN_1D_fu_110_Layer1_WeightArray_V_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer1_WeightArray_V_EN_A : STD_LOGIC;
    signal grp_CNN_1D_fu_110_Layer1_WeightArray_V_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer1_WeightArray_V_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_CNN_1D_fu_110_Layer1_BiasArray_V_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer1_BiasArray_V_EN_A : STD_LOGIC;
    signal grp_CNN_1D_fu_110_Layer1_BiasArray_V_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer1_BiasArray_V_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_EN_A : STD_LOGIC;
    signal grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_CNN_1D_fu_110_Layer2_BiasArray_V_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer2_BiasArray_V_EN_A : STD_LOGIC;
    signal grp_CNN_1D_fu_110_Layer2_BiasArray_V_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer2_BiasArray_V_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_weightArray_0_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_weightArray_0_EN_A : STD_LOGIC;
    signal grp_CNN_1D_fu_110_Layer3_weightArray_0_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_weightArray_0_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_weightArray_1_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_weightArray_1_EN_A : STD_LOGIC;
    signal grp_CNN_1D_fu_110_Layer3_weightArray_1_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_weightArray_1_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_weightArray_2_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_weightArray_2_EN_A : STD_LOGIC;
    signal grp_CNN_1D_fu_110_Layer3_weightArray_2_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_weightArray_2_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_weightArray_3_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_weightArray_3_EN_A : STD_LOGIC;
    signal grp_CNN_1D_fu_110_Layer3_weightArray_3_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_weightArray_3_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_Bias_V_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_Bias_V_EN_A : STD_LOGIC;
    signal grp_CNN_1D_fu_110_Layer3_Bias_V_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer3_Bias_V_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_CNN_1D_fu_110_Layer4_weightArray_V_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer4_weightArray_V_EN_A : STD_LOGIC;
    signal grp_CNN_1D_fu_110_Layer4_weightArray_V_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer4_weightArray_V_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_CNN_1D_fu_110_Layer4_Bias_V_Addr_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer4_Bias_V_EN_A : STD_LOGIC;
    signal grp_CNN_1D_fu_110_Layer4_Bias_V_Din_A : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CNN_1D_fu_110_Layer4_Bias_V_WEN_A : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_CNN_1D_fu_110_dst_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CNN_1D_fu_110_dst_V_ce0 : STD_LOGIC;
    signal grp_CNN_1D_fu_110_dst_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_CNN_1D_fu_110_dst_V_we0 : STD_LOGIC;
    signal grp_CNN_1D_fu_110_ap_done : STD_LOGIC;
    signal grp_CNN_1D_fu_110_ap_start : STD_LOGIC;
    signal grp_CNN_1D_fu_110_ap_ready : STD_LOGIC;
    signal grp_CNN_1D_fu_110_ap_idle : STD_LOGIC;
    signal grp_CNN_1D_fu_110_ap_continue : STD_LOGIC;
    signal i_reg_98 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_reg_grp_CNN_1D_fu_110_ap_start : STD_LOGIC := '0';
    signal exitcond_fu_166_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sync_reg_grp_CNN_1D_fu_110_ap_ready : STD_LOGIC := '0';
    signal ap_sync_grp_CNN_1D_fu_110_ap_ready : STD_LOGIC;
    signal tmp_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);

    component CNN_1D IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        src_V_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        src_V_ce0 : OUT STD_LOGIC;
        src_V_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        src_V_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
        src_V_we0 : OUT STD_LOGIC;
        src_V_offset : IN STD_LOGIC_VECTOR (7 downto 0);
        saveValueLayer1_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        saveValueLayer1_V_EN_A : OUT STD_LOGIC;
        saveValueLayer1_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        saveValueLayer1_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        saveValueLayer1_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        saveValueLayer2_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        saveValueLayer2_V_EN_A : OUT STD_LOGIC;
        saveValueLayer2_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        saveValueLayer2_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        saveValueLayer2_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        saveValueLayer3_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        saveValueLayer3_V_EN_A : OUT STD_LOGIC;
        saveValueLayer3_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        saveValueLayer3_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        saveValueLayer3_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        Layer1_WeightArray_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer1_WeightArray_V_EN_A : OUT STD_LOGIC;
        Layer1_WeightArray_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer1_WeightArray_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        Layer1_WeightArray_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        Layer1_BiasArray_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer1_BiasArray_V_EN_A : OUT STD_LOGIC;
        Layer1_BiasArray_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer1_BiasArray_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        Layer1_BiasArray_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        Layer2_WeightMatrix_s_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer2_WeightMatrix_s_EN_A : OUT STD_LOGIC;
        Layer2_WeightMatrix_s_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer2_WeightMatrix_s_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        Layer2_WeightMatrix_s_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        Layer2_BiasArray_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer2_BiasArray_V_EN_A : OUT STD_LOGIC;
        Layer2_BiasArray_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer2_BiasArray_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        Layer2_BiasArray_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        Layer3_weightArray_0_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer3_weightArray_0_EN_A : OUT STD_LOGIC;
        Layer3_weightArray_0_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer3_weightArray_0_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        Layer3_weightArray_0_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        Layer3_weightArray_1_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer3_weightArray_1_EN_A : OUT STD_LOGIC;
        Layer3_weightArray_1_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer3_weightArray_1_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        Layer3_weightArray_1_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        Layer3_weightArray_2_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer3_weightArray_2_EN_A : OUT STD_LOGIC;
        Layer3_weightArray_2_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer3_weightArray_2_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        Layer3_weightArray_2_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        Layer3_weightArray_3_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer3_weightArray_3_EN_A : OUT STD_LOGIC;
        Layer3_weightArray_3_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer3_weightArray_3_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        Layer3_weightArray_3_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        Layer3_Bias_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer3_Bias_V_EN_A : OUT STD_LOGIC;
        Layer3_Bias_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer3_Bias_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        Layer3_Bias_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        Layer4_weightArray_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer4_weightArray_V_EN_A : OUT STD_LOGIC;
        Layer4_weightArray_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer4_weightArray_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        Layer4_weightArray_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        Layer4_Bias_V_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer4_Bias_V_EN_A : OUT STD_LOGIC;
        Layer4_Bias_V_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
        Layer4_Bias_V_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
        Layer4_Bias_V_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
        dst_V_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        dst_V_ce0 : OUT STD_LOGIC;
        dst_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        dst_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        dst_V_we0 : OUT STD_LOGIC;
        src_V_offset_ap_vld : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component MASTER_CNN_BUS_A_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        Config_rep : OUT STD_LOGIC_VECTOR (7 downto 0);
        src_V_address0 : IN STD_LOGIC_VECTOR (15 downto 0);
        src_V_ce0 : IN STD_LOGIC;
        src_V_q0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        dst_V_address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        dst_V_ce0 : IN STD_LOGIC;
        dst_V_we0 : IN STD_LOGIC;
        dst_V_d0 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    MASTER_CNN_BUS_A_s_axi_U : component MASTER_CNN_BUS_A_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_BUS_A_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_BUS_A_DATA_WIDTH)
    port map (
        AWVALID => s_axi_BUS_A_AWVALID,
        AWREADY => s_axi_BUS_A_AWREADY,
        AWADDR => s_axi_BUS_A_AWADDR,
        WVALID => s_axi_BUS_A_WVALID,
        WREADY => s_axi_BUS_A_WREADY,
        WDATA => s_axi_BUS_A_WDATA,
        WSTRB => s_axi_BUS_A_WSTRB,
        ARVALID => s_axi_BUS_A_ARVALID,
        ARREADY => s_axi_BUS_A_ARREADY,
        ARADDR => s_axi_BUS_A_ARADDR,
        RVALID => s_axi_BUS_A_RVALID,
        RREADY => s_axi_BUS_A_RREADY,
        RDATA => s_axi_BUS_A_RDATA,
        RRESP => s_axi_BUS_A_RRESP,
        BVALID => s_axi_BUS_A_BVALID,
        BREADY => s_axi_BUS_A_BREADY,
        BRESP => s_axi_BUS_A_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        Config_rep => Config_rep,
        src_V_address0 => grp_CNN_1D_fu_110_src_V_address0,
        src_V_ce0 => grp_CNN_1D_fu_110_src_V_ce0,
        src_V_q0 => src_V_q0,
        dst_V_address0 => grp_CNN_1D_fu_110_dst_V_address0,
        dst_V_ce0 => grp_CNN_1D_fu_110_dst_V_ce0,
        dst_V_we0 => grp_CNN_1D_fu_110_dst_V_we0,
        dst_V_d0 => grp_CNN_1D_fu_110_dst_V_d0);

    grp_CNN_1D_fu_110 : component CNN_1D
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        src_V_address0 => grp_CNN_1D_fu_110_src_V_address0,
        src_V_ce0 => grp_CNN_1D_fu_110_src_V_ce0,
        src_V_d0 => grp_CNN_1D_fu_110_src_V_d0,
        src_V_q0 => src_V_q0,
        src_V_we0 => grp_CNN_1D_fu_110_src_V_we0,
        src_V_offset => i_reg_98,
        saveValueLayer1_V_Addr_A => grp_CNN_1D_fu_110_saveValueLayer1_V_Addr_A,
        saveValueLayer1_V_EN_A => grp_CNN_1D_fu_110_saveValueLayer1_V_EN_A,
        saveValueLayer1_V_Din_A => grp_CNN_1D_fu_110_saveValueLayer1_V_Din_A,
        saveValueLayer1_V_Dout_A => ap_const_lv32_0,
        saveValueLayer1_V_WEN_A => grp_CNN_1D_fu_110_saveValueLayer1_V_WEN_A,
        saveValueLayer2_V_Addr_A => grp_CNN_1D_fu_110_saveValueLayer2_V_Addr_A,
        saveValueLayer2_V_EN_A => grp_CNN_1D_fu_110_saveValueLayer2_V_EN_A,
        saveValueLayer2_V_Din_A => grp_CNN_1D_fu_110_saveValueLayer2_V_Din_A,
        saveValueLayer2_V_Dout_A => ap_const_lv32_0,
        saveValueLayer2_V_WEN_A => grp_CNN_1D_fu_110_saveValueLayer2_V_WEN_A,
        saveValueLayer3_V_Addr_A => grp_CNN_1D_fu_110_saveValueLayer3_V_Addr_A,
        saveValueLayer3_V_EN_A => grp_CNN_1D_fu_110_saveValueLayer3_V_EN_A,
        saveValueLayer3_V_Din_A => grp_CNN_1D_fu_110_saveValueLayer3_V_Din_A,
        saveValueLayer3_V_Dout_A => ap_const_lv32_0,
        saveValueLayer3_V_WEN_A => grp_CNN_1D_fu_110_saveValueLayer3_V_WEN_A,
        Layer1_WeightArray_V_Addr_A => grp_CNN_1D_fu_110_Layer1_WeightArray_V_Addr_A,
        Layer1_WeightArray_V_EN_A => grp_CNN_1D_fu_110_Layer1_WeightArray_V_EN_A,
        Layer1_WeightArray_V_Din_A => grp_CNN_1D_fu_110_Layer1_WeightArray_V_Din_A,
        Layer1_WeightArray_V_Dout_A => Layer1_WeightArray_V_Dout_A,
        Layer1_WeightArray_V_WEN_A => grp_CNN_1D_fu_110_Layer1_WeightArray_V_WEN_A,
        Layer1_BiasArray_V_Addr_A => grp_CNN_1D_fu_110_Layer1_BiasArray_V_Addr_A,
        Layer1_BiasArray_V_EN_A => grp_CNN_1D_fu_110_Layer1_BiasArray_V_EN_A,
        Layer1_BiasArray_V_Din_A => grp_CNN_1D_fu_110_Layer1_BiasArray_V_Din_A,
        Layer1_BiasArray_V_Dout_A => Layer1_BiasArray_V_Dout_A,
        Layer1_BiasArray_V_WEN_A => grp_CNN_1D_fu_110_Layer1_BiasArray_V_WEN_A,
        Layer2_WeightMatrix_s_Addr_A => grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_Addr_A,
        Layer2_WeightMatrix_s_EN_A => grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_EN_A,
        Layer2_WeightMatrix_s_Din_A => grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_Din_A,
        Layer2_WeightMatrix_s_Dout_A => Layer2_WeightMatrix_V_Dout_A,
        Layer2_WeightMatrix_s_WEN_A => grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_WEN_A,
        Layer2_BiasArray_V_Addr_A => grp_CNN_1D_fu_110_Layer2_BiasArray_V_Addr_A,
        Layer2_BiasArray_V_EN_A => grp_CNN_1D_fu_110_Layer2_BiasArray_V_EN_A,
        Layer2_BiasArray_V_Din_A => grp_CNN_1D_fu_110_Layer2_BiasArray_V_Din_A,
        Layer2_BiasArray_V_Dout_A => Layer2_BiasArray_V_Dout_A,
        Layer2_BiasArray_V_WEN_A => grp_CNN_1D_fu_110_Layer2_BiasArray_V_WEN_A,
        Layer3_weightArray_0_Addr_A => grp_CNN_1D_fu_110_Layer3_weightArray_0_Addr_A,
        Layer3_weightArray_0_EN_A => grp_CNN_1D_fu_110_Layer3_weightArray_0_EN_A,
        Layer3_weightArray_0_Din_A => grp_CNN_1D_fu_110_Layer3_weightArray_0_Din_A,
        Layer3_weightArray_0_Dout_A => Layer3_weightArray_0_V_Dout_A,
        Layer3_weightArray_0_WEN_A => grp_CNN_1D_fu_110_Layer3_weightArray_0_WEN_A,
        Layer3_weightArray_1_Addr_A => grp_CNN_1D_fu_110_Layer3_weightArray_1_Addr_A,
        Layer3_weightArray_1_EN_A => grp_CNN_1D_fu_110_Layer3_weightArray_1_EN_A,
        Layer3_weightArray_1_Din_A => grp_CNN_1D_fu_110_Layer3_weightArray_1_Din_A,
        Layer3_weightArray_1_Dout_A => Layer3_weightArray_1_V_Dout_A,
        Layer3_weightArray_1_WEN_A => grp_CNN_1D_fu_110_Layer3_weightArray_1_WEN_A,
        Layer3_weightArray_2_Addr_A => grp_CNN_1D_fu_110_Layer3_weightArray_2_Addr_A,
        Layer3_weightArray_2_EN_A => grp_CNN_1D_fu_110_Layer3_weightArray_2_EN_A,
        Layer3_weightArray_2_Din_A => grp_CNN_1D_fu_110_Layer3_weightArray_2_Din_A,
        Layer3_weightArray_2_Dout_A => Layer3_weightArray_2_V_Dout_A,
        Layer3_weightArray_2_WEN_A => grp_CNN_1D_fu_110_Layer3_weightArray_2_WEN_A,
        Layer3_weightArray_3_Addr_A => grp_CNN_1D_fu_110_Layer3_weightArray_3_Addr_A,
        Layer3_weightArray_3_EN_A => grp_CNN_1D_fu_110_Layer3_weightArray_3_EN_A,
        Layer3_weightArray_3_Din_A => grp_CNN_1D_fu_110_Layer3_weightArray_3_Din_A,
        Layer3_weightArray_3_Dout_A => Layer3_weightArray_3_V_Dout_A,
        Layer3_weightArray_3_WEN_A => grp_CNN_1D_fu_110_Layer3_weightArray_3_WEN_A,
        Layer3_Bias_V_Addr_A => grp_CNN_1D_fu_110_Layer3_Bias_V_Addr_A,
        Layer3_Bias_V_EN_A => grp_CNN_1D_fu_110_Layer3_Bias_V_EN_A,
        Layer3_Bias_V_Din_A => grp_CNN_1D_fu_110_Layer3_Bias_V_Din_A,
        Layer3_Bias_V_Dout_A => Layer3_Bias_V_Dout_A,
        Layer3_Bias_V_WEN_A => grp_CNN_1D_fu_110_Layer3_Bias_V_WEN_A,
        Layer4_weightArray_V_Addr_A => grp_CNN_1D_fu_110_Layer4_weightArray_V_Addr_A,
        Layer4_weightArray_V_EN_A => grp_CNN_1D_fu_110_Layer4_weightArray_V_EN_A,
        Layer4_weightArray_V_Din_A => grp_CNN_1D_fu_110_Layer4_weightArray_V_Din_A,
        Layer4_weightArray_V_Dout_A => Layer4_weightArray_V_Dout_A,
        Layer4_weightArray_V_WEN_A => grp_CNN_1D_fu_110_Layer4_weightArray_V_WEN_A,
        Layer4_Bias_V_Addr_A => grp_CNN_1D_fu_110_Layer4_Bias_V_Addr_A,
        Layer4_Bias_V_EN_A => grp_CNN_1D_fu_110_Layer4_Bias_V_EN_A,
        Layer4_Bias_V_Din_A => grp_CNN_1D_fu_110_Layer4_Bias_V_Din_A,
        Layer4_Bias_V_Dout_A => Layer4_Bias_V_Dout_A,
        Layer4_Bias_V_WEN_A => grp_CNN_1D_fu_110_Layer4_Bias_V_WEN_A,
        dst_V_address0 => grp_CNN_1D_fu_110_dst_V_address0,
        dst_V_ce0 => grp_CNN_1D_fu_110_dst_V_ce0,
        dst_V_d0 => grp_CNN_1D_fu_110_dst_V_d0,
        dst_V_q0 => ap_const_lv16_0,
        dst_V_we0 => grp_CNN_1D_fu_110_dst_V_we0,
        src_V_offset_ap_vld => ap_const_logic_1,
        ap_done => grp_CNN_1D_fu_110_ap_done,
        ap_start => grp_CNN_1D_fu_110_ap_start,
        ap_ready => grp_CNN_1D_fu_110_ap_ready,
        ap_idle => grp_CNN_1D_fu_110_ap_idle,
        ap_continue => grp_CNN_1D_fu_110_ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_grp_CNN_1D_fu_110_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_grp_CNN_1D_fu_110_ap_start <= ap_const_logic_0;
            else
                if ((((ap_sync_grp_CNN_1D_fu_110_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((exitcond_fu_166_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
                    ap_reg_grp_CNN_1D_fu_110_ap_start <= ap_const_logic_1;
                elsif ((grp_CNN_1D_fu_110_ap_ready = ap_const_logic_1)) then 
                    ap_reg_grp_CNN_1D_fu_110_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_CNN_1D_fu_110_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_grp_CNN_1D_fu_110_ap_ready <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                    if ((grp_CNN_1D_fu_110_ap_done = ap_const_logic_1)) then 
                        ap_sync_reg_grp_CNN_1D_fu_110_ap_ready <= ap_const_logic_0;
                    elsif ((grp_CNN_1D_fu_110_ap_ready = ap_const_logic_1)) then 
                        ap_sync_reg_grp_CNN_1D_fu_110_ap_ready <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    i_reg_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_CNN_1D_fu_110_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_reg_98 <= i_1_reg_185;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_reg_98 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                Config_rep_s_reg_177 <= Config_rep_s_fu_158_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_1_reg_185 <= i_1_fu_171_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_CNN_1D_fu_110_ap_done, ap_CS_fsm_state3, exitcond_fu_166_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond_fu_166_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_CNN_1D_fu_110_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    Config_rep_s_fu_158_p3 <= 
        Config_rep when (tmp_fu_152_p2(0) = '1') else 
        ap_const_lv8_C8;
    Layer1_BiasArray_V_Addr_A <= grp_CNN_1D_fu_110_Layer1_BiasArray_V_Addr_A;
    Layer1_BiasArray_V_Clk_A <= ap_clk;
    Layer1_BiasArray_V_Din_A <= ap_const_lv32_0;
    Layer1_BiasArray_V_EN_A <= grp_CNN_1D_fu_110_Layer1_BiasArray_V_EN_A;
    Layer1_BiasArray_V_Rst_A <= ap_rst_n_inv;
    Layer1_BiasArray_V_WEN_A <= ap_const_lv4_0;
    Layer1_WeightArray_V_Addr_A <= grp_CNN_1D_fu_110_Layer1_WeightArray_V_Addr_A;
    Layer1_WeightArray_V_Clk_A <= ap_clk;
    Layer1_WeightArray_V_Din_A <= ap_const_lv32_0;
    Layer1_WeightArray_V_EN_A <= grp_CNN_1D_fu_110_Layer1_WeightArray_V_EN_A;
    Layer1_WeightArray_V_Rst_A <= ap_rst_n_inv;
    Layer1_WeightArray_V_WEN_A <= ap_const_lv4_0;
    Layer2_BiasArray_V_Addr_A <= grp_CNN_1D_fu_110_Layer2_BiasArray_V_Addr_A;
    Layer2_BiasArray_V_Clk_A <= ap_clk;
    Layer2_BiasArray_V_Din_A <= ap_const_lv32_0;
    Layer2_BiasArray_V_EN_A <= grp_CNN_1D_fu_110_Layer2_BiasArray_V_EN_A;
    Layer2_BiasArray_V_Rst_A <= ap_rst_n_inv;
    Layer2_BiasArray_V_WEN_A <= ap_const_lv4_0;
    Layer2_WeightMatrix_V_Addr_A <= grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_Addr_A;
    Layer2_WeightMatrix_V_Clk_A <= ap_clk;
    Layer2_WeightMatrix_V_Din_A <= ap_const_lv32_0;
    Layer2_WeightMatrix_V_EN_A <= grp_CNN_1D_fu_110_Layer2_WeightMatrix_s_EN_A;
    Layer2_WeightMatrix_V_Rst_A <= ap_rst_n_inv;
    Layer2_WeightMatrix_V_WEN_A <= ap_const_lv4_0;
    Layer3_Bias_V_Addr_A <= grp_CNN_1D_fu_110_Layer3_Bias_V_Addr_A;
    Layer3_Bias_V_Clk_A <= ap_clk;
    Layer3_Bias_V_Din_A <= ap_const_lv32_0;
    Layer3_Bias_V_EN_A <= grp_CNN_1D_fu_110_Layer3_Bias_V_EN_A;
    Layer3_Bias_V_Rst_A <= ap_rst_n_inv;
    Layer3_Bias_V_WEN_A <= ap_const_lv4_0;
    Layer3_weightArray_0_V_Addr_A <= grp_CNN_1D_fu_110_Layer3_weightArray_0_Addr_A;
    Layer3_weightArray_0_V_Clk_A <= ap_clk;
    Layer3_weightArray_0_V_Din_A <= ap_const_lv32_0;
    Layer3_weightArray_0_V_EN_A <= grp_CNN_1D_fu_110_Layer3_weightArray_0_EN_A;
    Layer3_weightArray_0_V_Rst_A <= ap_rst_n_inv;
    Layer3_weightArray_0_V_WEN_A <= ap_const_lv4_0;
    Layer3_weightArray_1_V_Addr_A <= grp_CNN_1D_fu_110_Layer3_weightArray_1_Addr_A;
    Layer3_weightArray_1_V_Clk_A <= ap_clk;
    Layer3_weightArray_1_V_Din_A <= ap_const_lv32_0;
    Layer3_weightArray_1_V_EN_A <= grp_CNN_1D_fu_110_Layer3_weightArray_1_EN_A;
    Layer3_weightArray_1_V_Rst_A <= ap_rst_n_inv;
    Layer3_weightArray_1_V_WEN_A <= ap_const_lv4_0;
    Layer3_weightArray_2_V_Addr_A <= grp_CNN_1D_fu_110_Layer3_weightArray_2_Addr_A;
    Layer3_weightArray_2_V_Clk_A <= ap_clk;
    Layer3_weightArray_2_V_Din_A <= ap_const_lv32_0;
    Layer3_weightArray_2_V_EN_A <= grp_CNN_1D_fu_110_Layer3_weightArray_2_EN_A;
    Layer3_weightArray_2_V_Rst_A <= ap_rst_n_inv;
    Layer3_weightArray_2_V_WEN_A <= ap_const_lv4_0;
    Layer3_weightArray_3_V_Addr_A <= grp_CNN_1D_fu_110_Layer3_weightArray_3_Addr_A;
    Layer3_weightArray_3_V_Clk_A <= ap_clk;
    Layer3_weightArray_3_V_Din_A <= ap_const_lv32_0;
    Layer3_weightArray_3_V_EN_A <= grp_CNN_1D_fu_110_Layer3_weightArray_3_EN_A;
    Layer3_weightArray_3_V_Rst_A <= ap_rst_n_inv;
    Layer3_weightArray_3_V_WEN_A <= ap_const_lv4_0;
    Layer4_Bias_V_Addr_A <= grp_CNN_1D_fu_110_Layer4_Bias_V_Addr_A;
    Layer4_Bias_V_Clk_A <= ap_clk;
    Layer4_Bias_V_Din_A <= ap_const_lv32_0;
    Layer4_Bias_V_EN_A <= grp_CNN_1D_fu_110_Layer4_Bias_V_EN_A;
    Layer4_Bias_V_Rst_A <= ap_rst_n_inv;
    Layer4_Bias_V_WEN_A <= ap_const_lv4_0;
    Layer4_weightArray_V_Addr_A <= grp_CNN_1D_fu_110_Layer4_weightArray_V_Addr_A;
    Layer4_weightArray_V_Clk_A <= ap_clk;
    Layer4_weightArray_V_Din_A <= ap_const_lv32_0;
    Layer4_weightArray_V_EN_A <= grp_CNN_1D_fu_110_Layer4_weightArray_V_EN_A;
    Layer4_weightArray_V_Rst_A <= ap_rst_n_inv;
    Layer4_weightArray_V_WEN_A <= ap_const_lv4_0;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_done_assign_proc : process(ap_CS_fsm_state2, exitcond_fu_166_p2)
    begin
        if (((exitcond_fu_166_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, exitcond_fu_166_p2)
    begin
        if (((exitcond_fu_166_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sync_grp_CNN_1D_fu_110_ap_ready_assign_proc : process(grp_CNN_1D_fu_110_ap_ready, ap_sync_reg_grp_CNN_1D_fu_110_ap_ready)
    begin
        if ((ap_sync_reg_grp_CNN_1D_fu_110_ap_ready = ap_const_logic_0)) then 
            ap_sync_grp_CNN_1D_fu_110_ap_ready <= grp_CNN_1D_fu_110_ap_ready;
        else 
            ap_sync_grp_CNN_1D_fu_110_ap_ready <= ap_const_logic_1;
        end if; 
    end process;

    exitcond_fu_166_p2 <= "1" when (i_reg_98 = Config_rep_s_reg_177) else "0";

    grp_CNN_1D_fu_110_ap_continue_assign_proc : process(grp_CNN_1D_fu_110_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_CNN_1D_fu_110_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            grp_CNN_1D_fu_110_ap_continue <= ap_const_logic_1;
        else 
            grp_CNN_1D_fu_110_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_CNN_1D_fu_110_ap_start <= ap_reg_grp_CNN_1D_fu_110_ap_start;
    i_1_fu_171_p2 <= std_logic_vector(unsigned(i_reg_98) + unsigned(ap_const_lv8_1));
    saveValueLayer1_V_Addr_A <= grp_CNN_1D_fu_110_saveValueLayer1_V_Addr_A;
    saveValueLayer1_V_Clk_A <= ap_clk;
    saveValueLayer1_V_Din_A <= grp_CNN_1D_fu_110_saveValueLayer1_V_Din_A;
    saveValueLayer1_V_EN_A <= grp_CNN_1D_fu_110_saveValueLayer1_V_EN_A;
    saveValueLayer1_V_Rst_A <= ap_rst_n_inv;
    saveValueLayer1_V_WEN_A <= grp_CNN_1D_fu_110_saveValueLayer1_V_WEN_A;
    saveValueLayer2_V_Addr_A <= grp_CNN_1D_fu_110_saveValueLayer2_V_Addr_A;
    saveValueLayer2_V_Clk_A <= ap_clk;
    saveValueLayer2_V_Din_A <= grp_CNN_1D_fu_110_saveValueLayer2_V_Din_A;
    saveValueLayer2_V_EN_A <= grp_CNN_1D_fu_110_saveValueLayer2_V_EN_A;
    saveValueLayer2_V_Rst_A <= ap_rst_n_inv;
    saveValueLayer2_V_WEN_A <= grp_CNN_1D_fu_110_saveValueLayer2_V_WEN_A;
    saveValueLayer3_V_Addr_A <= grp_CNN_1D_fu_110_saveValueLayer3_V_Addr_A;
    saveValueLayer3_V_Clk_A <= ap_clk;
    saveValueLayer3_V_Din_A <= grp_CNN_1D_fu_110_saveValueLayer3_V_Din_A;
    saveValueLayer3_V_EN_A <= grp_CNN_1D_fu_110_saveValueLayer3_V_EN_A;
    saveValueLayer3_V_Rst_A <= ap_rst_n_inv;
    saveValueLayer3_V_WEN_A <= grp_CNN_1D_fu_110_saveValueLayer3_V_WEN_A;
    tmp_fu_152_p2 <= "1" when (unsigned(Config_rep) < unsigned(ap_const_lv8_C8)) else "0";
end behav;
